/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models

import dev.clientapi.pve.models.PveBoolean

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param userid Full User ID, in the `name@realm` format.
 * @param comment 
 * @param email 
 * @param enable Enable the account (default). You can set this to '0' to disable the account
 * @param expire Account expiration date (seconds since epoch). '0' means no expiration date.
 * @param firstname 
 * @param groups 
 * @param propertyKeys Keys for two factor auth (yubico).
 * @param lastname 
 * @param password Initial password.
 */


data class AccessUsersCreateUserRequest (

    /* Full User ID, in the `name@realm` format. */
    @Json(name = "userid")
    val userid: kotlin.String,

    @Json(name = "comment")
    val comment: kotlin.String? = null,

    @Json(name = "email")
    val email: kotlin.String? = null,

    /* Enable the account (default). You can set this to '0' to disable the account */
    @Json(name = "enable")
    val enable: PveBoolean? = null,

    /* Account expiration date (seconds since epoch). '0' means no expiration date. */
    @Json(name = "expire")
    val expire: kotlin.Long? = null,

    @Json(name = "firstname")
    val firstname: kotlin.String? = null,

    @Json(name = "groups")
    val groups: kotlin.String? = null,

    /* Keys for two factor auth (yubico). */
    @Json(name = "keys")
    val propertyKeys: kotlin.String? = null,

    @Json(name = "lastname")
    val lastname: kotlin.String? = null,

    /* Initial password. */
    @Json(name = "password")
    val password: kotlin.String? = null

) {


}

