/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param authid UserId or token
 * @param path Verify ticket, and check if user have access 'privs' on 'path'
 * @param privs Verify ticket, and check if user have access 'privs' on 'path'
 * @param vncticket The VNC ticket.
 */


data class AccessVerifyVncTicketRequest (

    /* UserId or token */
    @Json(name = "authid")
    val authid: kotlin.String,

    /* Verify ticket, and check if user have access 'privs' on 'path' */
    @Json(name = "path")
    val path: kotlin.String,

    /* Verify ticket, and check if user have access 'privs' on 'path' */
    @Json(name = "privs")
    val privs: kotlin.String,

    /* The VNC ticket. */
    @Json(name = "vncticket")
    val vncticket: kotlin.String

) {


}

