/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models

import dev.clientapi.pve.models.PveLinkField

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param clustername The name of the cluster.
 * @param link0 Address and priority information of a single corosync link. (up to 8 links supported; link0..link7)
 * @param link1 Address and priority information of a single corosync link. (up to 8 links supported; link0..link7)
 * @param link2 Address and priority information of a single corosync link. (up to 8 links supported; link0..link7)
 * @param link3 Address and priority information of a single corosync link. (up to 8 links supported; link0..link7)
 * @param link4 Address and priority information of a single corosync link. (up to 8 links supported; link0..link7)
 * @param link5 Address and priority information of a single corosync link. (up to 8 links supported; link0..link7)
 * @param link6 Address and priority information of a single corosync link. (up to 8 links supported; link0..link7)
 * @param link7 Address and priority information of a single corosync link. (up to 8 links supported; link0..link7)
 * @param nodeid Node id for this node.
 * @param votes Number of votes for this node.
 */


data class ClusterConfigCreateConfigRequest (

    /* The name of the cluster. */
    @Json(name = "clustername")
    val clustername: kotlin.String,

    /* Address and priority information of a single corosync link. (up to 8 links supported; link0..link7) */
    @Json(name = "link0")
    internal val link0: PveLinkField? = null,

    /* Address and priority information of a single corosync link. (up to 8 links supported; link0..link7) */
    @Json(name = "link1")
    internal val link1: PveLinkField? = null,

    /* Address and priority information of a single corosync link. (up to 8 links supported; link0..link7) */
    @Json(name = "link2")
    internal val link2: PveLinkField? = null,

    /* Address and priority information of a single corosync link. (up to 8 links supported; link0..link7) */
    @Json(name = "link3")
    internal val link3: PveLinkField? = null,

    /* Address and priority information of a single corosync link. (up to 8 links supported; link0..link7) */
    @Json(name = "link4")
    internal val link4: PveLinkField? = null,

    /* Address and priority information of a single corosync link. (up to 8 links supported; link0..link7) */
    @Json(name = "link5")
    internal val link5: PveLinkField? = null,

    /* Address and priority information of a single corosync link. (up to 8 links supported; link0..link7) */
    @Json(name = "link6")
    internal val link6: PveLinkField? = null,

    /* Address and priority information of a single corosync link. (up to 8 links supported; link0..link7) */
    @Json(name = "link7")
    internal val link7: PveLinkField? = null,

    /* Node id for this node. */
    @Json(name = "nodeid")
    val nodeid: kotlin.Long? = null,

    /* Number of votes for this node. */
    @Json(name = "votes")
    val votes: kotlin.Long? = null

) {


}


/** Read the links family (link0..link7) as a sparse `Map<Int, PveLinkField>`. */
public fun ClusterConfigCreateConfigRequest.getLinks(): kotlin.collections.Map<kotlin.Int, PveLinkField> {
    val out = kotlin.collections.mutableMapOf<kotlin.Int, PveLinkField>()
    link0?.let { out[0] = it }
    link1?.let { out[1] = it }
    link2?.let { out[2] = it }
    link3?.let { out[3] = it }
    link4?.let { out[4] = it }
    link5?.let { out[5] = it }
    link6?.let { out[6] = it }
    link7?.let { out[7] = it }
    return out
}

public fun ClusterConfigCreateConfigRequest.withLinks(items: kotlin.collections.Map<kotlin.Int, PveLinkField>): ClusterConfigCreateConfigRequest = this.copy(
    link0 = items[0],
    link1 = items[1],
    link2 = items[2],
    link3 = items[3],
    link4 = items[4],
    link5 = items[5],
    link6 = items[6],
    link7 = items[7],
)
