/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models

import dev.clientapi.pve.models.PveAffinityEnum
import dev.clientapi.pve.models.PveBoolean
import dev.clientapi.pve.models.PveClusterHaTypeTypeEnum2

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param resources List of HA resource IDs. This consists of a list of resource types followed by a resource specific name separated with a colon (example: vm:100,ct:101).
 * @param rule HA rule identifier.
 * @param type HA rule type.
 * @param affinity Describes whether the HA resources are supposed to be kept on the same node ('positive'), or are supposed to be kept on separate nodes ('negative').
 * @param comment HA rule description.
 * @param disable Whether the HA rule is disabled.
 * @param nodes List of cluster node members, where a priority can be given to each node. A resource will run on the available nodes with the highest priority. If there are more nodes in the highest priority class, the resources will get distributed to those nodes. The priorities have a relative meaning only. The higher the number, the higher the priority.
 * @param strict Describes whether the node affinity rule is strict or non-strict.  A non-strict node affinity rule makes resources prefer to be on the defined nodes. If none of the defined nodes are available, the resource may run on any other node.  A strict node affinity rule makes resources be restricted to the defined nodes. If none of the defined nodes are available, the resource will be stopped. 
 */


data class ClusterHaCreateRuleRequest (

    /* List of HA resource IDs. This consists of a list of resource types followed by a resource specific name separated with a colon (example: vm:100,ct:101). */
    @Json(name = "resources")
    val resources: kotlin.String,

    /* HA rule identifier. */
    @Json(name = "rule")
    val rule: kotlin.String,

    /* HA rule type. */
    @Json(name = "type")
    val type: PveClusterHaTypeTypeEnum2,

    /* Describes whether the HA resources are supposed to be kept on the same node ('positive'), or are supposed to be kept on separate nodes ('negative'). */
    @Json(name = "affinity")
    val affinity: PveAffinityEnum? = null,

    /* HA rule description. */
    @Json(name = "comment")
    val comment: kotlin.String? = null,

    /* Whether the HA rule is disabled. */
    @Json(name = "disable")
    val disable: PveBoolean? = null,

    /* List of cluster node members, where a priority can be given to each node. A resource will run on the available nodes with the highest priority. If there are more nodes in the highest priority class, the resources will get distributed to those nodes. The priorities have a relative meaning only. The higher the number, the higher the priority. */
    @Json(name = "nodes")
    val nodes: kotlin.String? = null,

    /* Describes whether the node affinity rule is strict or non-strict.  A non-strict node affinity rule makes resources prefer to be on the defined nodes. If none of the defined nodes are available, the resource may run on any other node.  A strict node affinity rule makes resources be restricted to the defined nodes. If none of the defined nodes are available, the resource will be stopped.  */
    @Json(name = "strict")
    val strict: PveBoolean? = null

) {


}

