/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models

import dev.clientapi.pve.models.PveBoolean

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param comment Comment
 * @param delete A list of settings you want to delete.
 * @param digest Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications.
 * @param disable Disable this target
 * @param server Server URL
 * @param token Secret token
 */


data class ClusterNotificationsUpdateGotifyEndpointRequest (

    /* Comment */
    @Json(name = "comment")
    val comment: kotlin.String? = null,

    /* A list of settings you want to delete. */
    @Json(name = "delete")
    val delete: kotlin.collections.List<kotlin.String>? = null,

    /* Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications. */
    @Json(name = "digest")
    val digest: kotlin.String? = null,

    /* Disable this target */
    @Json(name = "disable")
    val disable: PveBoolean? = null,

    /* Server URL */
    @Json(name = "server")
    val server: kotlin.String? = null,

    /* Secret token */
    @Json(name = "token")
    val token: kotlin.String? = null

) {


}

