/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models

import dev.clientapi.pve.models.PveClusterBackupInfoTypeEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type Type of the guest.
 * @param vmid VMID of the guest.
 * @param name Name of the guest
 */


data class ClusterBackupInfoGetGuestsNotInBackupResponseDataInner (

    /* Type of the guest. */
    @Json(name = "type")
    val type: PveClusterBackupInfoTypeEnum,

    /* VMID of the guest. */
    @Json(name = "vmid")
    val vmid: kotlin.Long,

    /* Name of the guest */
    @Json(name = "name")
    val name: kotlin.String? = null

) {


}

