/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models

import dev.clientapi.pve.models.PveBoolean
import dev.clientapi.pve.models.PveInfluxdbprotoEnum
import dev.clientapi.pve.models.PveOtelCompressionEnum
import dev.clientapi.pve.models.PveOtelProtocolEnum
import dev.clientapi.pve.models.PveProtoEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param port server network port
 * @param server server dns name or IP address
 * @param apiPathPrefix An API path prefix inserted between '<host>:<port>/' and '/api2/'. Can be useful if the InfluxDB service runs behind a reverse proxy.
 * @param bucket The InfluxDB bucket/db. Only necessary when using the http v2 api.
 * @param delete A list of settings you want to delete.
 * @param digest Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications.
 * @param disable Flag to disable the plugin.
 * @param influxdbproto 
 * @param maxBodySize InfluxDB max-body-size in bytes. Requests are batched up to this size.
 * @param mtu MTU for metrics transmission over UDP
 * @param organization The InfluxDB organization. Only necessary when using the http v2 api. Has no meaning when using v2 compatibility api.
 * @param otelCompression Compression algorithm for requests
 * @param otelHeaders Custom HTTP headers (JSON format, base64 encoded)
 * @param otelMaxBodySize Maximum request body size in bytes
 * @param otelPath OTLP endpoint path
 * @param otelProtocol HTTP protocol
 * @param otelResourceAttributes Additional resource attributes as JSON, base64 encoded
 * @param otelTimeout HTTP request timeout in seconds
 * @param otelVerifySsl Verify SSL certificates
 * @param path root graphite path (ex: proxmox.mycluster.mykey)
 * @param proto Protocol to send graphite data. TCP or UDP (default)
 * @param timeout graphite TCP socket timeout (default=1)
 * @param token The InfluxDB access token. Only necessary when using the http v2 api. If the v2 compatibility api is used, use 'user:password' instead.
 * @param verifyCertificate Set to 0 to disable certificate verification for https endpoints.
 */


data class ClusterMetricsUpdateServerRequest (

    /* server network port */
    @Json(name = "port")
    val port: kotlin.Int,

    /* server dns name or IP address */
    @Json(name = "server")
    val server: kotlin.String,

    /* An API path prefix inserted between '<host>:<port>/' and '/api2/'. Can be useful if the InfluxDB service runs behind a reverse proxy. */
    @Json(name = "api-path-prefix")
    val apiPathPrefix: kotlin.String? = null,

    /* The InfluxDB bucket/db. Only necessary when using the http v2 api. */
    @Json(name = "bucket")
    val bucket: kotlin.String? = null,

    /* A list of settings you want to delete. */
    @Json(name = "delete")
    val delete: kotlin.String? = null,

    /* Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications. */
    @Json(name = "digest")
    val digest: kotlin.String? = null,

    /* Flag to disable the plugin. */
    @Json(name = "disable")
    val disable: PveBoolean? = null,

    @Json(name = "influxdbproto")
    val influxdbproto: PveInfluxdbprotoEnum? = null,

    /* InfluxDB max-body-size in bytes. Requests are batched up to this size. */
    @Json(name = "max-body-size")
    val maxBodySize: kotlin.Long? = 25000000L,

    /* MTU for metrics transmission over UDP */
    @Json(name = "mtu")
    val mtu: kotlin.Int? = 1500,

    /* The InfluxDB organization. Only necessary when using the http v2 api. Has no meaning when using v2 compatibility api. */
    @Json(name = "organization")
    val organization: kotlin.String? = null,

    /* Compression algorithm for requests */
    @Json(name = "otel-compression")
    val otelCompression: PveOtelCompressionEnum? = null,

    /* Custom HTTP headers (JSON format, base64 encoded) */
    @Json(name = "otel-headers")
    val otelHeaders: kotlin.String? = null,

    /* Maximum request body size in bytes */
    @Json(name = "otel-max-body-size")
    val otelMaxBodySize: kotlin.Long? = 10000000L,

    /* OTLP endpoint path */
    @Json(name = "otel-path")
    val otelPath: kotlin.String? = "/v1/metrics",

    /* HTTP protocol */
    @Json(name = "otel-protocol")
    val otelProtocol: PveOtelProtocolEnum? = null,

    /* Additional resource attributes as JSON, base64 encoded */
    @Json(name = "otel-resource-attributes")
    val otelResourceAttributes: kotlin.String? = null,

    /* HTTP request timeout in seconds */
    @Json(name = "otel-timeout")
    val otelTimeout: kotlin.Int? = 5,

    /* Verify SSL certificates */
    @Json(name = "otel-verify-ssl")
    val otelVerifySsl: PveBoolean? = null,

    /* root graphite path (ex: proxmox.mycluster.mykey) */
    @Json(name = "path")
    val path: kotlin.String? = null,

    /* Protocol to send graphite data. TCP or UDP (default) */
    @Json(name = "proto")
    val proto: PveProtoEnum? = null,

    /* graphite TCP socket timeout (default=1) */
    @Json(name = "timeout")
    val timeout: kotlin.Long? = 1L,

    /* The InfluxDB access token. Only necessary when using the http v2 api. If the v2 compatibility api is used, use 'user:password' instead. */
    @Json(name = "token")
    val token: kotlin.String? = null,

    /* Set to 0 to disable certificate verification for https endpoints. */
    @Json(name = "verify-certificate")
    val verifyCertificate: PveBoolean? = null

) {


}

