/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models

import dev.clientapi.pve.models.ClusterMappingCreateDirRequestMapInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param delete A list of settings you want to delete.
 * @param description Description of the directory mapping
 * @param digest Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications.
 * @param map A list of maps for the cluster nodes.
 */


data class ClusterMappingUpdateDirRequest (

    /* A list of settings you want to delete. */
    @Json(name = "delete")
    val delete: kotlin.String? = null,

    /* Description of the directory mapping */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications. */
    @Json(name = "digest")
    val digest: kotlin.String? = null,

    /* A list of maps for the cluster nodes. */
    @Json(name = "map")
    val map: kotlin.collections.List<ClusterMappingCreateDirRequestMapInner>? = null

) {


}

