/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models

import dev.clientapi.pve.models.PveSdnIpamNetboxConfig
import dev.clientapi.pve.models.PveSdnIpamPhpipamConfig
import dev.clientapi.pve.models.PveSdnIpamPveConfig

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param url 
 * @param token 
 * @param section 
 * @param fingerprint Certificate SHA 256 fingerprint.
 */


interface ClusterSdnCreateIpamsRequest {

    @Json(name = "type")
    val type: ClusterSdnCreateIpamsRequest.Type
    @Json(name = "url")
    val url: kotlin.String
    @Json(name = "token")
    val token: kotlin.String
    @Json(name = "section")
    val section: kotlin.Long
    /* Certificate SHA 256 fingerprint. */
    @Json(name = "fingerprint")
    val fingerprint: kotlin.String?
    /**
     * 
     *
     * Values: pve,netbox,phpipam
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "pve") pve("pve"),
        @Json(name = "netbox") netbox("netbox"),
        @Json(name = "phpipam") phpipam("phpipam");
    }

}

