/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models

import dev.clientapi.pve.models.PveBoolean
import dev.clientapi.pve.models.PveClusterSdnTypeEnum2

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param subnet The SDN subnet object identifier.
 * @param type 
 * @param dhcpDnsServer IP address for the DNS server
 * @param dhcpRange A list of DHCP ranges for this subnet
 * @param dnszoneprefix dns domain zone prefix  ex: 'adm' -> <hostname>.adm.mydomain.com
 * @param gateway Subnet Gateway: Will be assign on vnet for layer3 zones
 * @param lockToken the token for unlocking the global SDN configuration
 * @param snat enable masquerade for this subnet if pve-firewall
 */


data class ClusterSdnCreateSubnetsRequest (

    /* The SDN subnet object identifier. */
    @Json(name = "subnet")
    val subnet: kotlin.String,

    @Json(name = "type")
    val type: PveClusterSdnTypeEnum2,

    /* IP address for the DNS server */
    @Json(name = "dhcp-dns-server")
    val dhcpDnsServer: kotlin.String? = null,

    /* A list of DHCP ranges for this subnet */
    @Json(name = "dhcp-range")
    val dhcpRange: kotlin.collections.List<kotlin.String>? = null,

    /* dns domain zone prefix  ex: 'adm' -> <hostname>.adm.mydomain.com */
    @Json(name = "dnszoneprefix")
    val dnszoneprefix: kotlin.String? = null,

    /* Subnet Gateway: Will be assign on vnet for layer3 zones */
    @Json(name = "gateway")
    val gateway: kotlin.String? = null,

    /* the token for unlocking the global SDN configuration */
    @Json(name = "lock-token")
    val lockToken: kotlin.String? = null,

    /* enable masquerade for this subnet if pve-firewall */
    @Json(name = "snat")
    val snat: PveBoolean? = null

) {


}

