/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models

import dev.clientapi.pve.models.PveBoolean

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param target Target node.
 * @param maxworkers How many parallel tasks at maximum should be started.
 * @param online Enable live migration for VMs and restart migration for CTs.
 * @param vms Only consider guests from this list of VMIDs.
 * @param withLocalDisks Enable live storage migration for local disk
 */


data class ClusterBulkActionMigrateRequest (

    /* Target node. */
    @Json(name = "target")
    val target: kotlin.String,

    /* How many parallel tasks at maximum should be started. */
    @Json(name = "maxworkers")
    val maxworkers: kotlin.Long? = 1L,

    /* Enable live migration for VMs and restart migration for CTs. */
    @Json(name = "online")
    val online: PveBoolean? = null,

    /* Only consider guests from this list of VMIDs. */
    @Json(name = "vms")
    val vms: kotlin.collections.List<kotlin.Int>? = null,

    /* Enable live storage migration for local disk */
    @Json(name = "with-local-disks")
    val withLocalDisks: PveBoolean? = null

) {


}

