/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models

import dev.clientapi.pve.models.ClusterHaRelocateResponseDataBlockingResourcesInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param requestedNode Node, which was requested to be relocated to.
 * @param sid HA resource, which is requested to be relocated.
 * @param blockingResources HA resources, which are blocking the given HA resource from being relocated to the requested target node.
 * @param comigratedResources HA resources, which are relocated to the same requested target node as the given HA resource, because these are in positive affinity with the HA resource.
 */


data class ClusterHaRelocateResponseData (

    /* Node, which was requested to be relocated to. */
    @Json(name = "requested-node")
    val requestedNode: kotlin.String,

    /* HA resource, which is requested to be relocated. */
    @Json(name = "sid")
    val sid: kotlin.String,

    /* HA resources, which are blocking the given HA resource from being relocated to the requested target node. */
    @Json(name = "blocking-resources")
    val blockingResources: kotlin.collections.List<ClusterHaRelocateResponseDataBlockingResourcesInner>? = null,

    /* HA resources, which are relocated to the same requested target node as the given HA resource, because these are in positive affinity with the HA resource. */
    @Json(name = "comigrated-resources")
    val comigratedResources: kotlin.collections.List<kotlin.String>? = null

) {


}

