/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models

import dev.clientapi.pve.models.PveBoolean
import dev.clientapi.pve.models.PveScopeEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param schedule Backup schedule. The format is a subset of `systemd` calendar events.
 * @param comment Description for the Job.
 * @param delete A list of settings you want to delete.
 * @param enableNew Enable newly synced users immediately.
 * @param enabled Determines if the job is enabled.
 * @param removeVanished A semicolon-separated list of things to remove when they or the user vanishes during a sync. The following values are possible: 'entry' removes the user/group when not returned from the sync. 'properties' removes the set properties on existing user/group that do not appear in the source (even custom ones). 'acl' removes acls when the user/group is not returned from the sync. Instead of a list it also can be 'none' (the default).
 * @param scope Select what to sync.
 */


data class ClusterJobsUpdateJobRequest (

    /* Backup schedule. The format is a subset of `systemd` calendar events. */
    @Json(name = "schedule")
    val schedule: kotlin.String,

    /* Description for the Job. */
    @Json(name = "comment")
    val comment: kotlin.String? = null,

    /* A list of settings you want to delete. */
    @Json(name = "delete")
    val delete: kotlin.String? = null,

    /* Enable newly synced users immediately. */
    @Json(name = "enable-new")
    val enableNew: PveBoolean? = null,

    /* Determines if the job is enabled. */
    @Json(name = "enabled")
    val enabled: PveBoolean? = null,

    /* A semicolon-separated list of things to remove when they or the user vanishes during a sync. The following values are possible: 'entry' removes the user/group when not returned from the sync. 'properties' removes the set properties on existing user/group that do not appear in the source (even custom ones). 'acl' removes acls when the user/group is not returned from the sync. Instead of a list it also can be 'none' (the default). */
    @Json(name = "remove-vanished")
    val removeVanished: kotlin.String? = "none",

    /* Select what to sync. */
    @Json(name = "scope")
    val scope: PveScopeEnum? = null

) {


}

