/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models

import dev.clientapi.pve.models.PveClusterSdnTypeTypeEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dns The SDN dns object identifier.
 * @param key 
 * @param type Plugin type.
 * @param url 
 * @param fingerprint Certificate SHA 256 fingerprint.
 * @param lockToken the token for unlocking the global SDN configuration
 * @param reversemaskv6 
 * @param reversev6mask 
 * @param ttl 
 */


data class ClusterSdnCreateDnsRequest (

    /* The SDN dns object identifier. */
    @Json(name = "dns")
    val dns: kotlin.String,

    @Json(name = "key")
    val key: kotlin.String,

    /* Plugin type. */
    @Json(name = "type")
    val type: PveClusterSdnTypeTypeEnum,

    @Json(name = "url")
    val url: kotlin.String,

    /* Certificate SHA 256 fingerprint. */
    @Json(name = "fingerprint")
    val fingerprint: kotlin.String? = null,

    /* the token for unlocking the global SDN configuration */
    @Json(name = "lock-token")
    val lockToken: kotlin.String? = null,

    @Json(name = "reversemaskv6")
    val reversemaskv6: kotlin.Long? = null,

    @Json(name = "reversev6mask")
    val reversev6mask: kotlin.Long? = null,

    @Json(name = "ttl")
    val ttl: kotlin.Long? = null

) {


}

