/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models

import dev.clientapi.pve.models.ClusterSdnGetControllersResponseDataInnerPending
import dev.clientapi.pve.models.PveBoolean
import dev.clientapi.pve.models.PveClusterSdnStateEnum
import dev.clientapi.pve.models.PveClusterSdnTypeEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param controller Name of the controller.
 * @param type Type of the controller
 * @param asn The local ASN of the controller. BGP & EVPN only.
 * @param bgpMultipathAsRelax Consider different AS paths of equal length for multipath computation. BGP only.
 * @param digest Digest of the controller section.
 * @param ebgp Enable eBGP (remote-as external). BGP only.
 * @param ebgpMultihop Set maximum amount of hops for eBGP peers. Needs ebgp set to 1. BGP only.
 * @param isisDomain Name of the IS-IS domain. IS-IS only.
 * @param isisIfaces Comma-separated list of interfaces where IS-IS should be active. IS-IS only.
 * @param isisNet Network Entity title for this node in the IS-IS network. IS-IS only.
 * @param loopback Name of the loopback/dummy interface that provides the Router-IP. BGP only.
 * @param node Node(s) where this controller is active.
 * @param peers Comma-separated list of the peers IP addresses.
 * @param pending 
 * @param state State of the SDN configuration object.
 */


data class ClusterSdnGetControllersResponseDataInner (

    /* Name of the controller. */
    @Json(name = "controller")
    val controller: kotlin.String,

    /* Type of the controller */
    @Json(name = "type")
    val type: PveClusterSdnTypeEnum,

    /* The local ASN of the controller. BGP & EVPN only. */
    @Json(name = "asn")
    val asn: kotlin.Int? = null,

    /* Consider different AS paths of equal length for multipath computation. BGP only. */
    @Json(name = "bgp-multipath-as-relax")
    val bgpMultipathAsRelax: PveBoolean? = null,

    /* Digest of the controller section. */
    @Json(name = "digest")
    val digest: kotlin.String? = null,

    /* Enable eBGP (remote-as external). BGP only. */
    @Json(name = "ebgp")
    val ebgp: PveBoolean? = null,

    /* Set maximum amount of hops for eBGP peers. Needs ebgp set to 1. BGP only. */
    @Json(name = "ebgp-multihop")
    val ebgpMultihop: kotlin.Long? = null,

    /* Name of the IS-IS domain. IS-IS only. */
    @Json(name = "isis-domain")
    val isisDomain: kotlin.String? = null,

    /* Comma-separated list of interfaces where IS-IS should be active. IS-IS only. */
    @Json(name = "isis-ifaces")
    val isisIfaces: kotlin.String? = null,

    /* Network Entity title for this node in the IS-IS network. IS-IS only. */
    @Json(name = "isis-net")
    val isisNet: kotlin.String? = null,

    /* Name of the loopback/dummy interface that provides the Router-IP. BGP only. */
    @Json(name = "loopback")
    val loopback: kotlin.String? = null,

    /* Node(s) where this controller is active. */
    @Json(name = "node")
    val node: kotlin.String? = null,

    /* Comma-separated list of the peers IP addresses. */
    @Json(name = "peers")
    val peers: kotlin.String? = null,

    @Json(name = "pending")
    val pending: ClusterSdnGetControllersResponseDataInnerPending? = null,

    /* State of the SDN configuration object. */
    @Json(name = "state")
    val state: PveClusterSdnStateEnum? = null

) {


}

