/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models

import dev.clientapi.pve.models.ClusterMappingGetDirResponseDataInnerChecksInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param description A description of the logical mapping.
 * @param id The logical ID of the mapping.
 * @param map The entries of the mapping.
 * @param checks A list of checks, only present if 'check_node' is set.
 */


data class ClusterMappingGetPciResponseDataInner (

    /* A description of the logical mapping. */
    @Json(name = "description")
    val description: kotlin.String,

    /* The logical ID of the mapping. */
    @Json(name = "id")
    val id: kotlin.String,

    /* The entries of the mapping. */
    @Json(name = "map")
    val map: kotlin.collections.List<kotlin.String>,

    /* A list of checks, only present if 'check_node' is set. */
    @Json(name = "checks")
    val checks: kotlin.collections.List<ClusterMappingGetDirResponseDataInnerChecksInner>? = null

) {


}

