/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models

import dev.clientapi.pve.models.LxcIpResponseDataInnerIpAddressesInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param hardwareAddress The MAC address of the interface
 * @param hwaddr The MAC address of the interface
 * @param ipAddresses The addresses of the interface
 * @param name The name of the interface
 * @param inet The IPv4 address of the interface
 * @param inet6 The IPv6 address of the interface
 */


data class LxcIpResponseDataInner (

    /* The MAC address of the interface */
    @Json(name = "hardware-address")
    val hardwareAddress: kotlin.String,

    /* The MAC address of the interface */
    @Json(name = "hwaddr")
    val hwaddr: kotlin.String,

    /* The addresses of the interface */
    @Json(name = "ip-addresses")
    val ipAddresses: kotlin.collections.List<LxcIpResponseDataInnerIpAddressesInner>,

    /* The name of the interface */
    @Json(name = "name")
    val name: kotlin.String,

    /* The IPv4 address of the interface */
    @Json(name = "inet")
    val inet: kotlin.String? = null,

    /* The IPv6 address of the interface */
    @Json(name = "inet6")
    val inet6: kotlin.String? = null

) {


}

