/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models

import dev.clientapi.pve.models.LxcMigrateVmPreconditionResponseDataNotAllowedNodes
import dev.clientapi.pve.models.PveBoolean

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param running Determines if the container is running.
 * @param allowedNodes List of nodes allowed for migration.
 * @param dependentHaResources HA resources, which will be migrated to the same target node as the VM, because these are in positive affinity with the VM.
 * @param notAllowedNodes 
 */


data class LxcMigrateVmPreconditionResponseData (

    /* Determines if the container is running. */
    @Json(name = "running")
    val running: PveBoolean,

    /* List of nodes allowed for migration. */
    @Json(name = "allowed-nodes")
    val allowedNodes: kotlin.collections.List<kotlin.String>? = null,

    /* HA resources, which will be migrated to the same target node as the VM, because these are in positive affinity with the VM. */
    @Json(name = "dependent-ha-resources")
    val dependentHaResources: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "not-allowed-nodes")
    val notAllowedNodes: LxcMigrateVmPreconditionResponseDataNotAllowedNodes? = null

) {


}

