/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models

import dev.clientapi.pve.models.PveBoolean

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param targetBridge Mapping from source to target bridges. Providing only a single bridge ID maps all source bridges to that bridge. Providing the special value '1' will map each source bridge to itself.
 * @param targetEndpoint Remote target endpoint
 * @param targetStorage Mapping from source to target storages. Providing only a single storage ID maps all source storages to that storage. Providing the special value '1' will map each source storage to itself.
 * @param bwlimit Override I/O bandwidth limit (in KiB/s).
 * @param delete Delete the original CT and related data after successful migration. By default the original CT is kept on the source cluster in a stopped state.
 * @param online Use online/live migration.
 * @param restart Use restart migration
 * @param targetVmid The (unique) ID of the VM.
 * @param timeout Timeout in seconds for shutdown for restart migration
 */


data class LxcRemoteMigrateVmRequest (

    /* Mapping from source to target bridges. Providing only a single bridge ID maps all source bridges to that bridge. Providing the special value '1' will map each source bridge to itself. */
    @Json(name = "target-bridge")
    val targetBridge: kotlin.String,

    /* Remote target endpoint */
    @Json(name = "target-endpoint")
    val targetEndpoint: kotlin.String,

    /* Mapping from source to target storages. Providing only a single storage ID maps all source storages to that storage. Providing the special value '1' will map each source storage to itself. */
    @Json(name = "target-storage")
    val targetStorage: kotlin.String,

    /* Override I/O bandwidth limit (in KiB/s). */
    @Json(name = "bwlimit")
    val bwlimit: java.math.BigDecimal? = null,

    /* Delete the original CT and related data after successful migration. By default the original CT is kept on the source cluster in a stopped state. */
    @Json(name = "delete")
    val delete: PveBoolean? = null,

    /* Use online/live migration. */
    @Json(name = "online")
    val online: PveBoolean? = null,

    /* Use restart migration */
    @Json(name = "restart")
    val restart: PveBoolean? = null,

    /* The (unique) ID of the VM. */
    @Json(name = "target-vmid")
    val targetVmid: kotlin.Int? = null,

    /* Timeout in seconds for shutdown for restart migration */
    @Json(name = "timeout")
    val timeout: kotlin.Long? = 180L

) {


}

