/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models

import dev.clientapi.pve.models.PveBoolean

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param filepath base64 path of the current entry
 * @param leaf If this entry is a leaf in the directory graph.
 * @param text Entry display text.
 * @param type Entry type.
 * @param mtime Entry last-modified time (unix timestamp).
 * @param propertySize Entry file size.
 */


data class NodesStorageGetListResponseDataInner (

    /* base64 path of the current entry */
    @Json(name = "filepath")
    val filepath: kotlin.String,

    /* If this entry is a leaf in the directory graph. */
    @Json(name = "leaf")
    val leaf: PveBoolean,

    /* Entry display text. */
    @Json(name = "text")
    val text: kotlin.String,

    /* Entry type. */
    @Json(name = "type")
    val type: kotlin.String,

    /* Entry last-modified time (unix timestamp). */
    @Json(name = "mtime")
    val mtime: kotlin.Long? = null,

    /* Entry file size. */
    @Json(name = "size")
    val propertySize: kotlin.Long? = null

) {


}

