/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name The name of the bridge port.
 * @param index The index of the guests network device that this interface belongs to.
 * @param primaryVlan The primary VLAN configured for the port of this bridge (= PVID). Only for VLAN-aware bridges.
 * @param vlans A list of VLANs and VLAN ranges that are allowed for this bridge port in addition to the primary VLAN. Only for VLAN-aware bridges.
 * @param vmid The ID of the guest that this interface belongs to.
 */


data class NodesSdnBridgesResponseDataInnerPortsInner (

    /* The name of the bridge port. */
    @Json(name = "name")
    val name: kotlin.String,

    /* The index of the guests network device that this interface belongs to. */
    @Json(name = "index")
    val index: kotlin.String? = null,

    /* The primary VLAN configured for the port of this bridge (= PVID). Only for VLAN-aware bridges. */
    @Json(name = "primary_vlan")
    val primaryVlan: java.math.BigDecimal? = null,

    /* A list of VLANs and VLAN ranges that are allowed for this bridge port in addition to the primary VLAN. Only for VLAN-aware bridges. */
    @Json(name = "vlans")
    val vlans: kotlin.collections.List<kotlin.String>? = null,

    /* The ID of the guest that this interface belongs to. */
    @Json(name = "vmid")
    val vmid: java.math.BigDecimal? = null

) {


}

