/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models

import dev.clientapi.pve.models.PveApplicationEnum
import dev.clientapi.pve.models.PvePgAutoscaleModeEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param application The application of the pool.
 * @param crushRule The rule to use for mapping object placement in the cluster.
 * @param minSize Minimum number of replicas per object
 * @param pgAutoscaleMode The automatic PG scaling mode of the pool.
 * @param pgNum Number of placement groups.
 * @param pgNumMin Minimal number of placement groups.
 * @param propertySize Number of replicas per object
 * @param targetSize The estimated target size of the pool for the PG autoscaler.
 * @param targetSizeRatio The estimated target ratio of the pool for the PG autoscaler.
 */


data class NodesCephSetpoolRequest (

    /* The application of the pool. */
    @Json(name = "application")
    val application: PveApplicationEnum? = null,

    /* The rule to use for mapping object placement in the cluster. */
    @Json(name = "crush_rule")
    val crushRule: kotlin.String? = null,

    /* Minimum number of replicas per object */
    @Json(name = "min_size")
    val minSize: kotlin.Int? = null,

    /* The automatic PG scaling mode of the pool. */
    @Json(name = "pg_autoscale_mode")
    val pgAutoscaleMode: PvePgAutoscaleModeEnum? = null,

    /* Number of placement groups. */
    @Json(name = "pg_num")
    val pgNum: kotlin.Int? = null,

    /* Minimal number of placement groups. */
    @Json(name = "pg_num_min")
    val pgNumMin: kotlin.Int? = null,

    /* Number of replicas per object */
    @Json(name = "size")
    val propertySize: kotlin.Int? = null,

    /* The estimated target size of the pool for the PG autoscaler. */
    @Json(name = "target_size")
    val targetSize: kotlin.String? = null,

    /* The estimated target ratio of the pool for the PG autoscaler. */
    @Json(name = "target_size_ratio")
    val targetSizeRatio: java.math.BigDecimal? = null

) {


}

