/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name The name (ID) for the MGR
 * @param state State of the MGR
 * @param addr 
 * @param host 
 */


data class NodesCephGetMgrResponseDataInner (

    /* The name (ID) for the MGR */
    @Json(name = "name")
    val name: kotlin.String,

    /* State of the MGR */
    @Json(name = "state")
    val state: kotlin.String,

    @Json(name = "addr")
    val addr: kotlin.String? = null,

    @Json(name = "host")
    val host: kotlin.String? = null

) {


}

