/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param node 
 * @param pid 
 * @param pstart 
 * @param starttime 
 * @param type 
 * @param upid 
 * @param user 
 * @param endtime 
 * @param status 
 */


data class NodesTasksNodeTasksResponseDataInner (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "node")
    val node: kotlin.String,

    @Json(name = "pid")
    val pid: kotlin.Long,

    @Json(name = "pstart")
    val pstart: kotlin.Long,

    @Json(name = "starttime")
    val starttime: kotlin.Long,

    @Json(name = "type")
    val type: kotlin.String,

    @Json(name = "upid")
    val upid: kotlin.String,

    @Json(name = "user")
    val user: kotlin.String,

    @Json(name = "endtime")
    val endtime: kotlin.Long? = null,

    @Json(name = "status")
    val status: kotlin.String? = null

) {


}

