/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models

import dev.clientapi.pve.models.NodesAptRepositoriesResponseDataErrorsInner
import dev.clientapi.pve.models.NodesAptRepositoriesResponseDataFilesInner
import dev.clientapi.pve.models.NodesAptRepositoriesResponseDataInfosInner
import dev.clientapi.pve.models.NodesAptRepositoriesResponseDataStandardReposInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param digest Common digest of all files.
 * @param errors List of problematic repository files.
 * @param files List of parsed repository files.
 * @param infos Additional information/warnings for APT repositories.
 * @param standardRepos List of standard repositories and their configuration status
 */


data class NodesAptRepositoriesResponseData (

    /* Common digest of all files. */
    @Json(name = "digest")
    val digest: kotlin.String,

    /* List of problematic repository files. */
    @Json(name = "errors")
    val errors: kotlin.collections.List<NodesAptRepositoriesResponseDataErrorsInner>,

    /* List of parsed repository files. */
    @Json(name = "files")
    val files: kotlin.collections.List<NodesAptRepositoriesResponseDataFilesInner>,

    /* Additional information/warnings for APT repositories. */
    @Json(name = "infos")
    val infos: kotlin.collections.List<NodesAptRepositoriesResponseDataInfosInner>,

    /* List of standard repositories and their configuration status */
    @Json(name = "standard-repos")
    val standardRepos: kotlin.collections.List<NodesAptRepositoriesResponseDataStandardReposInner>

) {


}

