/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models

import dev.clientapi.pve.models.PveBoolean

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param clusterNetwork Declare a separate cluster network, OSDs will routeheartbeat, object replication and recovery traffic over it
 * @param disableCephx Disable cephx authentication.  WARNING: cephx is a security feature protecting against man-in-the-middle attacks. Only consider disabling cephx if your network is private!
 * @param minSize Minimum number of available replicas per object to allow I/O
 * @param network Use specific network for all ceph related traffic
 * @param pgBits Placement group bits, used to specify the default number of placement groups.  Depreacted. This setting was deprecated in recent Ceph versions.
 * @param propertySize Targeted number of replicas per object
 */


data class NodesCephInitRequest (

    /* Declare a separate cluster network, OSDs will routeheartbeat, object replication and recovery traffic over it */
    @Json(name = "cluster-network")
    val clusterNetwork: kotlin.String? = null,

    /* Disable cephx authentication.  WARNING: cephx is a security feature protecting against man-in-the-middle attacks. Only consider disabling cephx if your network is private! */
    @Json(name = "disable_cephx")
    val disableCephx: PveBoolean? = null,

    /* Minimum number of available replicas per object to allow I/O */
    @Json(name = "min_size")
    val minSize: kotlin.Int? = 2,

    /* Use specific network for all ceph related traffic */
    @Json(name = "network")
    val network: kotlin.String? = null,

    /* Placement group bits, used to specify the default number of placement groups.  Depreacted. This setting was deprecated in recent Ceph versions. */
    @Json(name = "pg_bits")
    val pgBits: kotlin.Int? = 6,

    /* Targeted number of replicas per object */
    @Json(name = "size")
    val propertySize: kotlin.Int? = 3

) {


}

