/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models

import dev.clientapi.pve.models.NodesStorageGetContentResponseDataInnerVerification
import dev.clientapi.pve.models.PveBoolean

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param format Format identifier ('raw', 'qcow2', 'subvol', 'iso', 'tgz' ...)
 * @param propertySize Volume size in bytes.
 * @param volid Volume identifier.
 * @param ctime Creation time (seconds since the UNIX Epoch).
 * @param encrypted If whole backup is encrypted, value is the fingerprint or '1'  if encrypted. Only useful for the Proxmox Backup Server storage type.
 * @param notes Optional notes. If they contain multiple lines, only the first one is returned here.
 * @param parent Volume identifier of parent (for linked cloned).
 * @param `protected` Protection status. Currently only supported for backups.
 * @param used Used space. Please note that most storage plugins do not report anything useful here.
 * @param verification 
 * @param vmid Associated Owner VMID.
 */


data class NodesStorageGetContentResponseDataInner (

    /* Format identifier ('raw', 'qcow2', 'subvol', 'iso', 'tgz' ...) */
    @Json(name = "format")
    val format: kotlin.String,

    /* Volume size in bytes. */
    @Json(name = "size")
    val propertySize: kotlin.Long,

    /* Volume identifier. */
    @Json(name = "volid")
    val volid: kotlin.String,

    /* Creation time (seconds since the UNIX Epoch). */
    @Json(name = "ctime")
    val ctime: kotlin.Long? = null,

    /* If whole backup is encrypted, value is the fingerprint or '1'  if encrypted. Only useful for the Proxmox Backup Server storage type. */
    @Json(name = "encrypted")
    val encrypted: kotlin.String? = null,

    /* Optional notes. If they contain multiple lines, only the first one is returned here. */
    @Json(name = "notes")
    val notes: kotlin.String? = null,

    /* Volume identifier of parent (for linked cloned). */
    @Json(name = "parent")
    val parent: kotlin.String? = null,

    /* Protection status. Currently only supported for backups. */
    @Json(name = "protected")
    val `protected`: PveBoolean? = null,

    /* Used space. Please note that most storage plugins do not report anything useful here. */
    @Json(name = "used")
    val used: kotlin.Long? = null,

    @Json(name = "verification")
    val verification: NodesStorageGetContentResponseDataInnerVerification? = null,

    /* Associated Owner VMID. */
    @Json(name = "vmid")
    val vmid: kotlin.Long? = null

) {


}

