/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models

import dev.clientapi.pve.models.PvePoolsTypeTypeEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param node 
 * @param type 
 * @param storage 
 * @param vmid 
 */


data class PoolsGetPoolsResponseDataInnerMembersInner (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "node")
    val node: kotlin.String,

    @Json(name = "type")
    val type: PvePoolsTypeTypeEnum,

    @Json(name = "storage")
    val storage: kotlin.String? = null,

    @Json(name = "vmid")
    val vmid: kotlin.Long? = null

) {


}

