/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: armhf,arm64,amd64,ppc64el,risc64,s390x,all
 */

@JsonClass(generateAdapter = false)
enum class PveArchEnum(val value: kotlin.String) {

    @Json(name = "armhf")
    armhf("armhf"),

    @Json(name = "arm64")
    arm64("arm64"),

    @Json(name = "amd64")
    amd64("amd64"),

    @Json(name = "ppc64el")
    ppc64el("ppc64el"),

    @Json(name = "risc64")
    risc64("risc64"),

    @Json(name = "s390x")
    s390x("s390x"),

    @Json(name = "all")
    all("all");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PveArchEnum) "$data" else null

        /**
         * Returns a valid [PveArchEnum] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PveArchEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

