/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models

import dev.clientapi.pve.models.PveAioEnum
import dev.clientapi.pve.models.PveBoolean
import dev.clientapi.pve.models.PveCacheEnum
import dev.clientapi.pve.models.PveDiscardEnum
import dev.clientapi.pve.models.PveFormatEnum
import dev.clientapi.pve.models.PveMediaEnum
import dev.clientapi.pve.models.PveQemuVirtioConfig
import dev.clientapi.pve.models.PveRerrorEnum
import dev.clientapi.pve.models.PveWerrorEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param file The drive's backing volume.
 * @param aio AIO type to use.
 * @param backup Whether the drive should be included when making backups.
 * @param bps Maximum r/w speed in bytes per second.
 * @param bpsMaxLength Maximum length of I/O bursts in seconds.
 * @param bpsRd Maximum read speed in bytes per second.
 * @param bpsRdLength 
 * @param bpsRdMaxLength Maximum length of read I/O bursts in seconds.
 * @param bpsWr Maximum write speed in bytes per second.
 * @param bpsWrLength 
 * @param bpsWrMaxLength Maximum length of write I/O bursts in seconds.
 * @param cache The drive's cache mode
 * @param detectZeroes Controls whether to detect and try to optimize writes of zeroes.
 * @param discard Controls whether to pass discard/trim requests to the underlying storage.
 * @param format The drive's backing file's data format.
 * @param iops Maximum r/w I/O in operations per second.
 * @param iopsMax Maximum unthrottled r/w I/O pool in operations per second.
 * @param iopsMaxLength Maximum length of I/O bursts in seconds.
 * @param iopsRd Maximum read I/O in operations per second.
 * @param iopsRdLength 
 * @param iopsRdMax Maximum unthrottled read I/O pool in operations per second.
 * @param iopsRdMaxLength Maximum length of read I/O bursts in seconds.
 * @param iopsWr Maximum write I/O in operations per second.
 * @param iopsWrLength 
 * @param iopsWrMax Maximum unthrottled write I/O pool in operations per second.
 * @param iopsWrMaxLength Maximum length of write I/O bursts in seconds.
 * @param iothread Whether to use iothreads for this drive
 * @param mbps Maximum r/w speed in megabytes per second.
 * @param mbpsMax Maximum unthrottled r/w pool in megabytes per second.
 * @param mbpsRd Maximum read speed in megabytes per second.
 * @param mbpsRdMax Maximum unthrottled read pool in megabytes per second.
 * @param mbpsWr Maximum write speed in megabytes per second.
 * @param mbpsWrMax Maximum unthrottled write pool in megabytes per second.
 * @param media The drive's media type.
 * @param replicate Whether the drive should considered for replication jobs.
 * @param rerror Read error action.
 * @param ro Whether the drive is read-only.
 * @param serial The drive's reported serial number, url-encoded, up to 20 bytes long.
 * @param shared Mark this locally-managed volume as available on all nodes.  WARNING: This option does not share the volume automatically, it assumes it is shared already!
 * @param propertySize Disk size. This is purely informational and has no effect.
 * @param snapshot Controls qemu's snapshot mode feature. If activated, changes made to the disk are temporary and will be discarded when the VM is shutdown.
 * @param volume 
 * @param werror Write error action.
 */


data class PveQemuVirtioField (

    /* The drive's backing volume. */
    @Json(name = "file")
    val file: kotlin.String,

    /* AIO type to use. */
    @Json(name = "aio")
    val aio: PveAioEnum? = null,

    /* Whether the drive should be included when making backups. */
    @Json(name = "backup")
    val backup: PveBoolean? = null,

    /* Maximum r/w speed in bytes per second. */
    @Json(name = "bps")
    val bps: kotlin.Long? = null,

    /* Maximum length of I/O bursts in seconds. */
    @Json(name = "bps_max_length")
    val bpsMaxLength: kotlin.Long? = null,

    /* Maximum read speed in bytes per second. */
    @Json(name = "bps_rd")
    val bpsRd: kotlin.Long? = null,

    @Json(name = "bps_rd_length")
    val bpsRdLength: kotlin.String? = null,

    /* Maximum length of read I/O bursts in seconds. */
    @Json(name = "bps_rd_max_length")
    val bpsRdMaxLength: kotlin.Long? = null,

    /* Maximum write speed in bytes per second. */
    @Json(name = "bps_wr")
    val bpsWr: kotlin.Long? = null,

    @Json(name = "bps_wr_length")
    val bpsWrLength: kotlin.String? = null,

    /* Maximum length of write I/O bursts in seconds. */
    @Json(name = "bps_wr_max_length")
    val bpsWrMaxLength: kotlin.Long? = null,

    /* The drive's cache mode */
    @Json(name = "cache")
    val cache: PveCacheEnum? = null,

    /* Controls whether to detect and try to optimize writes of zeroes. */
    @Json(name = "detect_zeroes")
    val detectZeroes: PveBoolean? = null,

    /* Controls whether to pass discard/trim requests to the underlying storage. */
    @Json(name = "discard")
    val discard: PveDiscardEnum? = null,

    /* The drive's backing file's data format. */
    @Json(name = "format")
    val format: PveFormatEnum? = null,

    /* Maximum r/w I/O in operations per second. */
    @Json(name = "iops")
    val iops: kotlin.Long? = null,

    /* Maximum unthrottled r/w I/O pool in operations per second. */
    @Json(name = "iops_max")
    val iopsMax: kotlin.Long? = null,

    /* Maximum length of I/O bursts in seconds. */
    @Json(name = "iops_max_length")
    val iopsMaxLength: kotlin.Long? = null,

    /* Maximum read I/O in operations per second. */
    @Json(name = "iops_rd")
    val iopsRd: kotlin.Long? = null,

    @Json(name = "iops_rd_length")
    val iopsRdLength: kotlin.String? = null,

    /* Maximum unthrottled read I/O pool in operations per second. */
    @Json(name = "iops_rd_max")
    val iopsRdMax: kotlin.Long? = null,

    /* Maximum length of read I/O bursts in seconds. */
    @Json(name = "iops_rd_max_length")
    val iopsRdMaxLength: kotlin.Long? = null,

    /* Maximum write I/O in operations per second. */
    @Json(name = "iops_wr")
    val iopsWr: kotlin.Long? = null,

    @Json(name = "iops_wr_length")
    val iopsWrLength: kotlin.String? = null,

    /* Maximum unthrottled write I/O pool in operations per second. */
    @Json(name = "iops_wr_max")
    val iopsWrMax: kotlin.Long? = null,

    /* Maximum length of write I/O bursts in seconds. */
    @Json(name = "iops_wr_max_length")
    val iopsWrMaxLength: kotlin.Long? = null,

    /* Whether to use iothreads for this drive */
    @Json(name = "iothread")
    val iothread: PveBoolean? = null,

    /* Maximum r/w speed in megabytes per second. */
    @Json(name = "mbps")
    val mbps: java.math.BigDecimal? = null,

    /* Maximum unthrottled r/w pool in megabytes per second. */
    @Json(name = "mbps_max")
    val mbpsMax: java.math.BigDecimal? = null,

    /* Maximum read speed in megabytes per second. */
    @Json(name = "mbps_rd")
    val mbpsRd: java.math.BigDecimal? = null,

    /* Maximum unthrottled read pool in megabytes per second. */
    @Json(name = "mbps_rd_max")
    val mbpsRdMax: java.math.BigDecimal? = null,

    /* Maximum write speed in megabytes per second. */
    @Json(name = "mbps_wr")
    val mbpsWr: java.math.BigDecimal? = null,

    /* Maximum unthrottled write pool in megabytes per second. */
    @Json(name = "mbps_wr_max")
    val mbpsWrMax: java.math.BigDecimal? = null,

    /* The drive's media type. */
    @Json(name = "media")
    val media: PveMediaEnum? = null,

    /* Whether the drive should considered for replication jobs. */
    @Json(name = "replicate")
    val replicate: PveBoolean? = null,

    /* Read error action. */
    @Json(name = "rerror")
    val rerror: PveRerrorEnum? = null,

    /* Whether the drive is read-only. */
    @Json(name = "ro")
    val ro: PveBoolean? = null,

    /* The drive's reported serial number, url-encoded, up to 20 bytes long. */
    @Json(name = "serial")
    val serial: kotlin.String? = null,

    /* Mark this locally-managed volume as available on all nodes.  WARNING: This option does not share the volume automatically, it assumes it is shared already! */
    @Json(name = "shared")
    val shared: PveBoolean? = null,

    /* Disk size. This is purely informational and has no effect. */
    @Json(name = "size")
    val propertySize: kotlin.String? = null,

    /* Controls qemu's snapshot mode feature. If activated, changes made to the disk are temporary and will be discarded when the VM is shutdown. */
    @Json(name = "snapshot")
    val snapshot: PveBoolean? = null,

    @Json(name = "volume")
    val volume: kotlin.String? = null,

    /* Write error action. */
    @Json(name = "werror")
    val werror: PveWerrorEnum? = null

) {


}

