/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models

import dev.clientapi.pve.models.PveBoolean
import dev.clientapi.pve.models.PveUsbConfig

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param host The Host USB device or port or the value 'spice'. HOSTUSBDEVICE syntax is:   'bus-port(.port)*' (decimal numbers) or  'vendor_id:product_id' (hexadecimal numbers) or  'spice'  You can use the 'lsusb -t' command to list existing usb devices.  NOTE: This option allows direct access to host hardware. So it is no longer possible to migrate such machines - use with special care.  The value 'spice' can be used to add a usb redirection devices for spice.  Either this or the 'mapping' key must be set. 
 * @param mapping The ID of a cluster wide mapping. Either this or the default-key 'host' must be set.
 * @param usb3 Specifies whether if given host option is a USB3 device or port. For modern guests (machine version >= 7.1 and ostype l26 and windows > 7), this flag is irrelevant (all devices are plugged into a xhci controller).
 */


data class PveQemuUsbField (

    /* The Host USB device or port or the value 'spice'. HOSTUSBDEVICE syntax is:   'bus-port(.port)*' (decimal numbers) or  'vendor_id:product_id' (hexadecimal numbers) or  'spice'  You can use the 'lsusb -t' command to list existing usb devices.  NOTE: This option allows direct access to host hardware. So it is no longer possible to migrate such machines - use with special care.  The value 'spice' can be used to add a usb redirection devices for spice.  Either this or the 'mapping' key must be set.  */
    @Json(name = "host")
    val host: kotlin.String? = null,

    /* The ID of a cluster wide mapping. Either this or the default-key 'host' must be set. */
    @Json(name = "mapping")
    val mapping: kotlin.String? = null,

    /* Specifies whether if given host option is a USB3 device or port. For modern guests (machine version >= 7.1 and ostype l26 and windows > 7), this flag is irrelevant (all devices are plugged into a xhci controller). */
    @Json(name = "usb3")
    val usb3: PveBoolean? = null

) {


}

