/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models

import dev.clientapi.pve.models.PveBoolean
import dev.clientapi.pve.models.PveMachineConfig
import dev.clientapi.pve.models.PveViommuEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param awBits Specifies the vIOMMU address space bit width.  Intel vIOMMU supports a bit width of either 39 or 48 bits and VirtIO vIOMMU supports any bit width between 32 and 64 bits.
 * @param enableS3 Enables S3 power state. Defaults to false beginning with machine types 9.2+pve1, true before.
 * @param enableS4 Enables S4 power state. Defaults to false beginning with machine types 9.2+pve1, true before.
 * @param type Specifies the QEMU machine type.
 * @param viommu Enable and set guest vIOMMU variant (Intel vIOMMU needs q35 to be set as machine type).
 */


data class PveQemuMachineField (

    /* Specifies the vIOMMU address space bit width.  Intel vIOMMU supports a bit width of either 39 or 48 bits and VirtIO vIOMMU supports any bit width between 32 and 64 bits. */
    @Json(name = "aw-bits")
    val awBits: java.math.BigDecimal? = null,

    /* Enables S3 power state. Defaults to false beginning with machine types 9.2+pve1, true before. */
    @Json(name = "enable-s3")
    val enableS3: PveBoolean? = null,

    /* Enables S4 power state. Defaults to false beginning with machine types 9.2+pve1, true before. */
    @Json(name = "enable-s4")
    val enableS4: PveBoolean? = null,

    /* Specifies the QEMU machine type. */
    @Json(name = "type")
    val type: kotlin.String? = null,

    /* Enable and set guest vIOMMU variant (Intel vIOMMU needs q35 to be set as machine type). */
    @Json(name = "viommu")
    val viommu: PveViommuEnum? = null

) {


}

