/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models

import dev.clientapi.pve.models.PveClipboardEnum
import dev.clientapi.pve.models.PveQemuTypeTypeEnum
import dev.clientapi.pve.models.PveVgaConfig

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param clipboard Enable a specific clipboard. If not set, depending on the display type the SPICE one will be added. Migration with VNC clipboard is not yet supported!
 * @param memory Sets the VGA memory (in MiB). Has no effect with serial display.
 * @param type Select the VGA type. Using type 'cirrus' is not recommended.
 */


data class PveQemuVgaField (

    /* Enable a specific clipboard. If not set, depending on the display type the SPICE one will be added. Migration with VNC clipboard is not yet supported! */
    @Json(name = "clipboard")
    val clipboard: PveClipboardEnum? = null,

    /* Sets the VGA memory (in MiB). Has no effect with serial display. */
    @Json(name = "memory")
    val memory: kotlin.Int? = null,

    /* Select the VGA type. Using type 'cirrus' is not recommended. */
    @Json(name = "type")
    val type: PveQemuTypeTypeEnum? = null

) {


}

