/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: cirrus,qxl,qxl2,qxl3,qxl4,none,serial0,serial1,serial2,serial3,std,virtio,virtioMinusGl,vmware
 */

@JsonClass(generateAdapter = false)
enum class PveQemuTypeTypeEnum(val value: kotlin.String) {

    @Json(name = "cirrus")
    cirrus("cirrus"),

    @Json(name = "qxl")
    qxl("qxl"),

    @Json(name = "qxl2")
    qxl2("qxl2"),

    @Json(name = "qxl3")
    qxl3("qxl3"),

    @Json(name = "qxl4")
    qxl4("qxl4"),

    @Json(name = "none")
    none("none"),

    @Json(name = "serial0")
    serial0("serial0"),

    @Json(name = "serial1")
    serial1("serial1"),

    @Json(name = "serial2")
    serial2("serial2"),

    @Json(name = "serial3")
    serial3("serial3"),

    @Json(name = "std")
    std("std"),

    @Json(name = "virtio")
    virtio("virtio"),

    @Json(name = "virtio-gl")
    virtioMinusGl("virtio-gl"),

    @Json(name = "vmware")
    vmware("vmware");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PveQemuTypeTypeEnum) "$data" else null

        /**
         * Returns a valid [PveQemuTypeTypeEnum] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PveQemuTypeTypeEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

