/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models

import dev.clientapi.pve.models.PveBoolean
import dev.clientapi.pve.models.PveEfitypeEnum
import dev.clientapi.pve.models.PveFormatEnum
import dev.clientapi.pve.models.PveMsCertEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param file The drive's backing volume.
 * @param efitype Size and type of the OVMF EFI vars. '4m' is newer and recommended, and required for Secure Boot. For backwards compatibility, '2m' is used if not otherwise specified. Ignored for VMs with arch=aarch64 (ARM).
 * @param format The drive's backing file's data format.
 * @param msCert Informational marker indicating the version of the latest Microsof UEFI certificate that has been enrolled by Proxmox VE.
 * @param preEnrolledKeys Use am EFI vars template with distribution-specific and Microsoft Standard keys enrolled, if used with 'efitype=4m'. Note that this will enable Secure Boot by default, though it can still be turned off from within the VM.
 * @param propertySize Disk size. This is purely informational and has no effect.
 * @param volume 
 */


data class PveQemuEfidiskConfig (

    /* The drive's backing volume. */
    @Json(name = "file")
    val file: kotlin.String,

    /* Size and type of the OVMF EFI vars. '4m' is newer and recommended, and required for Secure Boot. For backwards compatibility, '2m' is used if not otherwise specified. Ignored for VMs with arch=aarch64 (ARM). */
    @Json(name = "efitype")
    val efitype: PveEfitypeEnum? = null,

    /* The drive's backing file's data format. */
    @Json(name = "format")
    val format: PveFormatEnum? = null,

    /* Informational marker indicating the version of the latest Microsof UEFI certificate that has been enrolled by Proxmox VE. */
    @Json(name = "ms-cert")
    val msCert: PveMsCertEnum? = null,

    /* Use am EFI vars template with distribution-specific and Microsoft Standard keys enrolled, if used with 'efitype=4m'. Note that this will enable Secure Boot by default, though it can still be turned off from within the VM. */
    @Json(name = "pre-enrolled-keys")
    val preEnrolledKeys: PveBoolean? = null,

    /* Disk size. This is purely informational and has no effect. */
    @Json(name = "size")
    val propertySize: kotlin.String? = null,

    @Json(name = "volume")
    val volume: kotlin.String? = null

) {


}

