/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models

import dev.clientapi.pve.models.PveBoolean

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param bridge The bridge for which VLANs should be managed.
 * @param type 
 * @param nodes List of cluster node names.
 * @param bridgeDisableMacLearning Disable auto mac learning.
 * @param mtu MTU of the zone, will be used for the created VNet bridges.
 * @param dns dns api server
 * @param reversedns reverse dns api server
 * @param dnszone dns domain zone  ex: mydomain.com
 * @param ipam use a specific ipam
 */


data class PveSdnZoneVlanConfig (

    /* The bridge for which VLANs should be managed. */
    @Json(name = "bridge")
    val bridge: kotlin.String,

    @Json(name = "type")
    val type: PveSdnZoneVlanConfig.Type,

    /* List of cluster node names. */
    @Json(name = "nodes")
    val nodes: kotlin.String? = null,

    /* Disable auto mac learning. */
    @Json(name = "bridge-disable-mac-learning")
    val bridgeDisableMacLearning: PveBoolean? = null,

    /* MTU of the zone, will be used for the created VNet bridges. */
    @Json(name = "mtu")
    val mtu: kotlin.Long? = null,

    /* dns api server */
    @Json(name = "dns")
    val dns: kotlin.String? = null,

    /* reverse dns api server */
    @Json(name = "reversedns")
    val reversedns: kotlin.String? = null,

    /* dns domain zone  ex: mydomain.com */
    @Json(name = "dnszone")
    val dnszone: kotlin.String? = null,

    /* use a specific ipam */
    @Json(name = "ipam")
    val ipam: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: vlan
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "vlan") vlan("vlan");
    }

}

