/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param isisDomain Name of the IS-IS domain.
 * @param isisNet Network Entity title for this node in the IS-IS network.
 * @param isisIfaces Comma-separated list of interfaces where IS-IS should be active.
 * @param node The cluster node name.
 * @param type 
 * @param loopback Name of the loopback/dummy interface that provides the Router-IP.
 */


data class PveSdnControllerIsisConfig (

    /* Name of the IS-IS domain. */
    @Json(name = "isis-domain")
    val isisDomain: kotlin.String,

    /* Network Entity title for this node in the IS-IS network. */
    @Json(name = "isis-net")
    val isisNet: kotlin.String,

    /* Comma-separated list of interfaces where IS-IS should be active. */
    @Json(name = "isis-ifaces")
    val isisIfaces: kotlin.String,

    /* The cluster node name. */
    @Json(name = "node")
    val node: kotlin.String,

    @Json(name = "type")
    val type: PveSdnControllerIsisConfig.Type,

    /* Name of the loopback/dummy interface that provides the Router-IP. */
    @Json(name = "loopback")
    val loopback: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: isis
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "isis") isis("isis");
    }

}

