/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models

import dev.clientapi.pve.models.PveBoolean

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param server Server IP or DNS name.
 * @param username RBD Id.
 * @param type 
 * @param nodes List of nodes for which the storage configuration applies.
 * @param shared Indicate that this is a single storage with the same contents on all nodes (or all listed in the 'nodes' option). It will not make the contents of a local storage automatically accessible to other nodes, it just marks an already shared storage as such!
 * @param disable Flag to disable the storage.
 * @param content Allowed content types.  NOTE: the value 'rootdir' is used for Containers, and value 'images' for VMs. 
 * @param password Password for accessing the share/datastore.
 * @param skipCertVerification Disable TLS certificate verification, only enable on fully trusted networks!
 * @param port Use this port to connect to the storage instead of the default one (for example, with PBS or ESXi). For NFS and CIFS, use the 'options' option to configure the port via the mount options.
 */


data class PveStorageEsxiConfig (

    /* Server IP or DNS name. */
    @Json(name = "server")
    val server: kotlin.String,

    /* RBD Id. */
    @Json(name = "username")
    val username: kotlin.String,

    @Json(name = "type")
    val type: PveStorageEsxiConfig.Type,

    /* List of nodes for which the storage configuration applies. */
    @Json(name = "nodes")
    val nodes: kotlin.String? = null,

    /* Indicate that this is a single storage with the same contents on all nodes (or all listed in the 'nodes' option). It will not make the contents of a local storage automatically accessible to other nodes, it just marks an already shared storage as such! */
    @Json(name = "shared")
    val shared: PveBoolean? = null,

    /* Flag to disable the storage. */
    @Json(name = "disable")
    val disable: PveBoolean? = null,

    /* Allowed content types.  NOTE: the value 'rootdir' is used for Containers, and value 'images' for VMs.  */
    @Json(name = "content")
    val content: kotlin.String? = null,

    /* Password for accessing the share/datastore. */
    @Json(name = "password")
    val password: kotlin.String? = null,

    /* Disable TLS certificate verification, only enable on fully trusted networks! */
    @Json(name = "skip-cert-verification")
    val skipCertVerification: PveBoolean? = null,

    /* Use this port to connect to the storage instead of the default one (for example, with PBS or ESXi). For NFS and CIFS, use the 'options' option to configure the port via the mount options. */
    @Json(name = "port")
    val port: kotlin.Int? = null

) {

    /**
     * 
     *
     * Values: esxi
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "esxi") esxi("esxi");
    }

}

