/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param url 
 * @param token 
 * @param section 
 * @param type 
 * @param fingerprint Certificate SHA 256 fingerprint.
 */


data class PveSdnIpamPhpipamConfig (

    @Json(name = "url")
    val url: kotlin.String,

    @Json(name = "token")
    val token: kotlin.String,

    @Json(name = "section")
    val section: kotlin.Long,

    @Json(name = "type")
    val type: PveSdnIpamPhpipamConfig.Type,

    /* Certificate SHA 256 fingerprint. */
    @Json(name = "fingerprint")
    val fingerprint: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: phpipam
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "phpipam") phpipam("phpipam");
    }

}

