/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models

import dev.clientapi.pve.models.PveBoolean
import dev.clientapi.pve.models.PveBwlimitField

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param pool Pool.
 * @param type 
 * @param blocksize block size
 * @param sparse use sparse volumes
 * @param nodes List of nodes for which the storage configuration applies.
 * @param disable Flag to disable the storage.
 * @param content Allowed content types.  NOTE: the value 'rootdir' is used for Containers, and value 'images' for VMs. 
 * @param bwlimit Set I/O bandwidth limit for various operations (in KiB/s).
 * @param mountpoint mount point
 */


data class PveStorageZfspoolConfig (

    /* Pool. */
    @Json(name = "pool")
    val pool: kotlin.String,

    @Json(name = "type")
    val type: PveStorageZfspoolConfig.Type,

    /* block size */
    @Json(name = "blocksize")
    val blocksize: kotlin.String? = null,

    /* use sparse volumes */
    @Json(name = "sparse")
    val sparse: PveBoolean? = null,

    /* List of nodes for which the storage configuration applies. */
    @Json(name = "nodes")
    val nodes: kotlin.String? = null,

    /* Flag to disable the storage. */
    @Json(name = "disable")
    val disable: PveBoolean? = null,

    /* Allowed content types.  NOTE: the value 'rootdir' is used for Containers, and value 'images' for VMs.  */
    @Json(name = "content")
    val content: kotlin.String? = null,

    /* Set I/O bandwidth limit for various operations (in KiB/s). */
    @Json(name = "bwlimit")
    val bwlimit: PveBwlimitField? = null,

    /* mount point */
    @Json(name = "mountpoint")
    val mountpoint: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: zfspool
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "zfspool") zfspool("zfspool");
    }

}

