/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models

import dev.clientapi.pve.models.PveBoolean
import dev.clientapi.pve.models.PveStatusEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param status QEMU process status.
 * @param vmid The (unique) ID of the VM.
 * @param cpu Current CPU usage.
 * @param cpus Maximum usable CPUs.
 * @param diskread The amount of bytes the guest read from it's block devices since the guest was started. (Note: This info is not available for all storage types.)
 * @param diskwrite The amount of bytes the guest wrote from it's block devices since the guest was started. (Note: This info is not available for all storage types.)
 * @param lock The current config lock, if any.
 * @param maxdisk Root disk size in bytes.
 * @param maxmem Maximum memory in bytes.
 * @param mem Currently used memory in bytes.
 * @param memhost Current memory usage on the host.
 * @param name VM (host)name.
 * @param netin The amount of traffic in bytes that was sent to the guest over the network since it was started.
 * @param netout The amount of traffic in bytes that was sent from the guest over the network since it was started.
 * @param pid PID of the QEMU process, if the VM is running.
 * @param pressurecpufull CPU Full pressure stall average over the last 10 seconds.
 * @param pressurecpusome CPU Some pressure stall average over the last 10 seconds.
 * @param pressureiofull IO Full pressure stall average over the last 10 seconds.
 * @param pressureiosome IO Some pressure stall average over the last 10 seconds.
 * @param pressurememoryfull Memory Full pressure stall average over the last 10 seconds.
 * @param pressurememorysome Memory Some pressure stall average over the last 10 seconds.
 * @param qmpstatus VM run state from the 'query-status' QMP monitor command.
 * @param runningMachine The currently running machine type (if running).
 * @param runningQemu The QEMU version the VM is currently using (if running).
 * @param serial Guest has serial device configured.
 * @param tags The current configured tags, if any
 * @param template Determines if the guest is a template.
 * @param uptime Uptime in seconds.
 */


data class QemuVmlistResponseDataInner (

    /* QEMU process status. */
    @Json(name = "status")
    val status: PveStatusEnum,

    /* The (unique) ID of the VM. */
    @Json(name = "vmid")
    val vmid: kotlin.Int,

    /* Current CPU usage. */
    @Json(name = "cpu")
    val cpu: java.math.BigDecimal? = null,

    /* Maximum usable CPUs. */
    @Json(name = "cpus")
    val cpus: java.math.BigDecimal? = null,

    /* The amount of bytes the guest read from it's block devices since the guest was started. (Note: This info is not available for all storage types.) */
    @Json(name = "diskread")
    val diskread: kotlin.Long? = null,

    /* The amount of bytes the guest wrote from it's block devices since the guest was started. (Note: This info is not available for all storage types.) */
    @Json(name = "diskwrite")
    val diskwrite: kotlin.Long? = null,

    /* The current config lock, if any. */
    @Json(name = "lock")
    val lock: kotlin.String? = null,

    /* Root disk size in bytes. */
    @Json(name = "maxdisk")
    val maxdisk: kotlin.Long? = null,

    /* Maximum memory in bytes. */
    @Json(name = "maxmem")
    val maxmem: kotlin.Long? = null,

    /* Currently used memory in bytes. */
    @Json(name = "mem")
    val mem: kotlin.Long? = null,

    /* Current memory usage on the host. */
    @Json(name = "memhost")
    val memhost: kotlin.Long? = null,

    /* VM (host)name. */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* The amount of traffic in bytes that was sent to the guest over the network since it was started. */
    @Json(name = "netin")
    val netin: kotlin.Long? = null,

    /* The amount of traffic in bytes that was sent from the guest over the network since it was started. */
    @Json(name = "netout")
    val netout: kotlin.Long? = null,

    /* PID of the QEMU process, if the VM is running. */
    @Json(name = "pid")
    val pid: kotlin.Long? = null,

    /* CPU Full pressure stall average over the last 10 seconds. */
    @Json(name = "pressurecpufull")
    val pressurecpufull: java.math.BigDecimal? = null,

    /* CPU Some pressure stall average over the last 10 seconds. */
    @Json(name = "pressurecpusome")
    val pressurecpusome: java.math.BigDecimal? = null,

    /* IO Full pressure stall average over the last 10 seconds. */
    @Json(name = "pressureiofull")
    val pressureiofull: java.math.BigDecimal? = null,

    /* IO Some pressure stall average over the last 10 seconds. */
    @Json(name = "pressureiosome")
    val pressureiosome: java.math.BigDecimal? = null,

    /* Memory Full pressure stall average over the last 10 seconds. */
    @Json(name = "pressurememoryfull")
    val pressurememoryfull: java.math.BigDecimal? = null,

    /* Memory Some pressure stall average over the last 10 seconds. */
    @Json(name = "pressurememorysome")
    val pressurememorysome: java.math.BigDecimal? = null,

    /* VM run state from the 'query-status' QMP monitor command. */
    @Json(name = "qmpstatus")
    val qmpstatus: kotlin.String? = null,

    /* The currently running machine type (if running). */
    @Json(name = "running-machine")
    val runningMachine: kotlin.String? = null,

    /* The QEMU version the VM is currently using (if running). */
    @Json(name = "running-qemu")
    val runningQemu: kotlin.String? = null,

    /* Guest has serial device configured. */
    @Json(name = "serial")
    val serial: PveBoolean? = null,

    /* The current configured tags, if any */
    @Json(name = "tags")
    val tags: kotlin.String? = null,

    /* Determines if the guest is a template. */
    @Json(name = "template")
    val template: PveBoolean? = null,

    /* Uptime in seconds. */
    @Json(name = "uptime")
    val uptime: kotlin.Long? = null

) {


}

