/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param command The command as a list of program + arguments.
 * @param inputData Data to pass as 'input-data' to the guest. Usually treated as STDIN to 'command'.
 */


data class QemuExecRequest (

    /* The command as a list of program + arguments. */
    @Json(name = "command")
    val command: kotlin.collections.List<kotlin.String>,

    /* Data to pass as 'input-data' to the guest. Usually treated as STDIN to 'command'. */
    @Json(name = "input-data")
    val inputData: kotlin.String? = null

) {


}

