/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.models

import dev.clientapi.pve.models.PveConsoleEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param release The current Proxmox VE point release in `x.y` format.
 * @param repoid The short git revision from which this version was build.
 * @param version The full pve-manager package version of this node.
 * @param console The default console viewer to use.
 */


data class VersionVersionResponseData (

    /* The current Proxmox VE point release in `x.y` format. */
    @Json(name = "release")
    val release: kotlin.String,

    /* The short git revision from which this version was build. */
    @Json(name = "repoid")
    val repoid: kotlin.String,

    /* The full pve-manager package version of this node. */
    @Json(name = "version")
    val version: kotlin.String,

    /* The default console viewer to use. */
    @Json(name = "console")
    val console: PveConsoleEnum? = null

) {


}

