/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import dev.clientapi.pve.models.ClusterHaCreateGroupsRequest
import dev.clientapi.pve.models.ClusterHaCreateGroupsResponse
import dev.clientapi.pve.models.ClusterHaCreateResourcesRequest
import dev.clientapi.pve.models.ClusterHaCreateResourcesResponse
import dev.clientapi.pve.models.ClusterHaCreateRuleRequest
import dev.clientapi.pve.models.ClusterHaCreateRuleResponse
import dev.clientapi.pve.models.ClusterHaDeleteGroupsResponse
import dev.clientapi.pve.models.ClusterHaDeleteResourcesResponse
import dev.clientapi.pve.models.ClusterHaDeleteRuleResponse
import dev.clientapi.pve.models.ClusterHaGetGroupsResponse
import dev.clientapi.pve.models.ClusterHaGetHaResponse
import dev.clientapi.pve.models.ClusterHaGetResourcesResponse
import dev.clientapi.pve.models.ClusterHaGetRulesResponse
import dev.clientapi.pve.models.ClusterHaGetStatusResponse
import dev.clientapi.pve.models.ClusterHaManagerStatusResponse
import dev.clientapi.pve.models.ClusterHaMigrateRequest
import dev.clientapi.pve.models.ClusterHaMigrateResponse
import dev.clientapi.pve.models.ClusterHaReadGetGroupsResponse
import dev.clientapi.pve.models.ClusterHaReadGetResourcesResponse
import dev.clientapi.pve.models.ClusterHaReadRuleResponse
import dev.clientapi.pve.models.ClusterHaRelocateResponse
import dev.clientapi.pve.models.ClusterHaStatusResponse
import dev.clientapi.pve.models.ClusterHaUpdateGroupsRequest
import dev.clientapi.pve.models.ClusterHaUpdateGroupsResponse
import dev.clientapi.pve.models.ClusterHaUpdateResourcesRequest
import dev.clientapi.pve.models.ClusterHaUpdateResourcesResponse
import dev.clientapi.pve.models.ClusterHaUpdateRuleRequest
import dev.clientapi.pve.models.ClusterHaUpdateRuleResponse
import dev.clientapi.pve.models.PveBoolean
import dev.clientapi.pve.models.PveClusterHaTypeTypeEnum
import dev.clientapi.pve.models.PveClusterHaTypeTypeEnum2
import dev.clientapi.pve.models.PveError

import com.squareup.moshi.Json

import dev.clientapi.pve.infrastructure.ApiClient
import dev.clientapi.pve.infrastructure.ApiResponse
import dev.clientapi.pve.infrastructure.ClientException
import dev.clientapi.pve.infrastructure.ClientError
import dev.clientapi.pve.infrastructure.ServerException
import dev.clientapi.pve.infrastructure.ServerError
import dev.clientapi.pve.infrastructure.MultiValueMap
import dev.clientapi.pve.infrastructure.PartConfig
import dev.clientapi.pve.infrastructure.RequestConfig
import dev.clientapi.pve.infrastructure.RequestMethod
import dev.clientapi.pve.infrastructure.ResponseType
import dev.clientapi.pve.infrastructure.Success
import dev.clientapi.pve.infrastructure.toMultiValue

open class ClusterHaApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8006/api2/json")
        }
    }

    /**
     * POST /cluster/ha/groups
     * Create a new HA group
     * Create a new HA group. (deprecated in favor of HA rules)
     * @param clusterHaCreateGroupsRequest 
     * @return ClusterHaCreateGroupsResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clusterHaCreateGroups(clusterHaCreateGroupsRequest: ClusterHaCreateGroupsRequest) : ClusterHaCreateGroupsResponse {
        val localVarResponse = clusterHaCreateGroupsWithHttpInfo(clusterHaCreateGroupsRequest = clusterHaCreateGroupsRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClusterHaCreateGroupsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /cluster/ha/groups
     * Create a new HA group
     * Create a new HA group. (deprecated in favor of HA rules)
     * @param clusterHaCreateGroupsRequest 
     * @return ApiResponse<ClusterHaCreateGroupsResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clusterHaCreateGroupsWithHttpInfo(clusterHaCreateGroupsRequest: ClusterHaCreateGroupsRequest) : ApiResponse<ClusterHaCreateGroupsResponse?> {
        val localVariableConfig = clusterHaCreateGroupsRequestConfig(clusterHaCreateGroupsRequest = clusterHaCreateGroupsRequest)

        return request<ClusterHaCreateGroupsRequest, ClusterHaCreateGroupsResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clusterHaCreateGroups
     *
     * @param clusterHaCreateGroupsRequest 
     * @return RequestConfig
     */
    fun clusterHaCreateGroupsRequestConfig(clusterHaCreateGroupsRequest: ClusterHaCreateGroupsRequest) : RequestConfig<ClusterHaCreateGroupsRequest> {
        val localVariableBody = clusterHaCreateGroupsRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/cluster/ha/groups",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /cluster/ha/resources
     * Create a new HA resource
     * Create a new HA resource.
     * @param clusterHaCreateResourcesRequest 
     * @return ClusterHaCreateResourcesResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clusterHaCreateResources(clusterHaCreateResourcesRequest: ClusterHaCreateResourcesRequest) : ClusterHaCreateResourcesResponse {
        val localVarResponse = clusterHaCreateResourcesWithHttpInfo(clusterHaCreateResourcesRequest = clusterHaCreateResourcesRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClusterHaCreateResourcesResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /cluster/ha/resources
     * Create a new HA resource
     * Create a new HA resource.
     * @param clusterHaCreateResourcesRequest 
     * @return ApiResponse<ClusterHaCreateResourcesResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clusterHaCreateResourcesWithHttpInfo(clusterHaCreateResourcesRequest: ClusterHaCreateResourcesRequest) : ApiResponse<ClusterHaCreateResourcesResponse?> {
        val localVariableConfig = clusterHaCreateResourcesRequestConfig(clusterHaCreateResourcesRequest = clusterHaCreateResourcesRequest)

        return request<ClusterHaCreateResourcesRequest, ClusterHaCreateResourcesResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clusterHaCreateResources
     *
     * @param clusterHaCreateResourcesRequest 
     * @return RequestConfig
     */
    fun clusterHaCreateResourcesRequestConfig(clusterHaCreateResourcesRequest: ClusterHaCreateResourcesRequest) : RequestConfig<ClusterHaCreateResourcesRequest> {
        val localVariableBody = clusterHaCreateResourcesRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/cluster/ha/resources",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /cluster/ha/rules
     * Create HA rule
     * Create HA rule.
     * @param clusterHaCreateRuleRequest 
     * @return ClusterHaCreateRuleResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clusterHaCreateRule(clusterHaCreateRuleRequest: ClusterHaCreateRuleRequest) : ClusterHaCreateRuleResponse {
        val localVarResponse = clusterHaCreateRuleWithHttpInfo(clusterHaCreateRuleRequest = clusterHaCreateRuleRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClusterHaCreateRuleResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /cluster/ha/rules
     * Create HA rule
     * Create HA rule.
     * @param clusterHaCreateRuleRequest 
     * @return ApiResponse<ClusterHaCreateRuleResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clusterHaCreateRuleWithHttpInfo(clusterHaCreateRuleRequest: ClusterHaCreateRuleRequest) : ApiResponse<ClusterHaCreateRuleResponse?> {
        val localVariableConfig = clusterHaCreateRuleRequestConfig(clusterHaCreateRuleRequest = clusterHaCreateRuleRequest)

        return request<ClusterHaCreateRuleRequest, ClusterHaCreateRuleResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clusterHaCreateRule
     *
     * @param clusterHaCreateRuleRequest 
     * @return RequestConfig
     */
    fun clusterHaCreateRuleRequestConfig(clusterHaCreateRuleRequest: ClusterHaCreateRuleRequest) : RequestConfig<ClusterHaCreateRuleRequest> {
        val localVariableBody = clusterHaCreateRuleRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/cluster/ha/rules",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /cluster/ha/groups/{group}
     * Delete ha group configuration
     * Delete ha group configuration. (deprecated in favor of HA rules)
     * @param group The HA group identifier.
     * @return ClusterHaDeleteGroupsResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clusterHaDeleteGroups(group: kotlin.String) : ClusterHaDeleteGroupsResponse {
        val localVarResponse = clusterHaDeleteGroupsWithHttpInfo(group = group)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClusterHaDeleteGroupsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /cluster/ha/groups/{group}
     * Delete ha group configuration
     * Delete ha group configuration. (deprecated in favor of HA rules)
     * @param group The HA group identifier.
     * @return ApiResponse<ClusterHaDeleteGroupsResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clusterHaDeleteGroupsWithHttpInfo(group: kotlin.String) : ApiResponse<ClusterHaDeleteGroupsResponse?> {
        val localVariableConfig = clusterHaDeleteGroupsRequestConfig(group = group)

        return request<Unit, ClusterHaDeleteGroupsResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clusterHaDeleteGroups
     *
     * @param group The HA group identifier.
     * @return RequestConfig
     */
    fun clusterHaDeleteGroupsRequestConfig(group: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/cluster/ha/groups/{group}".replace("{"+"group"+"}", encodeURIComponent(group.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /cluster/ha/resources/{sid}
     * Delete resource configuration
     * Delete resource configuration.
     * @param sid HA resource ID. This consists of a resource type followed by a resource specific name, separated with colon (example: vm:100 / ct:100). For virtual machines and containers, you can simply use the VM or CT id as a shortcut (example: 100).
     * @param purge Remove this resource from rules that reference it, deleting the rule if this resource is the only resource in the rule (optional)
     * @return ClusterHaDeleteResourcesResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clusterHaDeleteResources(sid: kotlin.String, purge: PveBoolean? = null) : ClusterHaDeleteResourcesResponse {
        val localVarResponse = clusterHaDeleteResourcesWithHttpInfo(sid = sid, purge = purge)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClusterHaDeleteResourcesResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /cluster/ha/resources/{sid}
     * Delete resource configuration
     * Delete resource configuration.
     * @param sid HA resource ID. This consists of a resource type followed by a resource specific name, separated with colon (example: vm:100 / ct:100). For virtual machines and containers, you can simply use the VM or CT id as a shortcut (example: 100).
     * @param purge Remove this resource from rules that reference it, deleting the rule if this resource is the only resource in the rule (optional)
     * @return ApiResponse<ClusterHaDeleteResourcesResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clusterHaDeleteResourcesWithHttpInfo(sid: kotlin.String, purge: PveBoolean?) : ApiResponse<ClusterHaDeleteResourcesResponse?> {
        val localVariableConfig = clusterHaDeleteResourcesRequestConfig(sid = sid, purge = purge)

        return request<Unit, ClusterHaDeleteResourcesResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clusterHaDeleteResources
     *
     * @param sid HA resource ID. This consists of a resource type followed by a resource specific name, separated with colon (example: vm:100 / ct:100). For virtual machines and containers, you can simply use the VM or CT id as a shortcut (example: 100).
     * @param purge Remove this resource from rules that reference it, deleting the rule if this resource is the only resource in the rule (optional)
     * @return RequestConfig
     */
    fun clusterHaDeleteResourcesRequestConfig(sid: kotlin.String, purge: PveBoolean?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (purge != null) {
                    put("purge", listOf(purge.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/cluster/ha/resources/{sid}".replace("{"+"sid"+"}", encodeURIComponent(sid.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /cluster/ha/rules/{rule}
     * Delete HA rule
     * Delete HA rule.
     * @param rule HA rule identifier.
     * @return ClusterHaDeleteRuleResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clusterHaDeleteRule(rule: kotlin.String) : ClusterHaDeleteRuleResponse {
        val localVarResponse = clusterHaDeleteRuleWithHttpInfo(rule = rule)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClusterHaDeleteRuleResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /cluster/ha/rules/{rule}
     * Delete HA rule
     * Delete HA rule.
     * @param rule HA rule identifier.
     * @return ApiResponse<ClusterHaDeleteRuleResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clusterHaDeleteRuleWithHttpInfo(rule: kotlin.String) : ApiResponse<ClusterHaDeleteRuleResponse?> {
        val localVariableConfig = clusterHaDeleteRuleRequestConfig(rule = rule)

        return request<Unit, ClusterHaDeleteRuleResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clusterHaDeleteRule
     *
     * @param rule HA rule identifier.
     * @return RequestConfig
     */
    fun clusterHaDeleteRuleRequestConfig(rule: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/cluster/ha/rules/{rule}".replace("{"+"rule"+"}", encodeURIComponent(rule.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /cluster/ha/groups
     * Get HA groups
     * Get HA groups. (deprecated in favor of HA rules)
     * @return ClusterHaGetGroupsResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clusterHaGetGroups() : ClusterHaGetGroupsResponse {
        val localVarResponse = clusterHaGetGroupsWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClusterHaGetGroupsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /cluster/ha/groups
     * Get HA groups
     * Get HA groups. (deprecated in favor of HA rules)
     * @return ApiResponse<ClusterHaGetGroupsResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clusterHaGetGroupsWithHttpInfo() : ApiResponse<ClusterHaGetGroupsResponse?> {
        val localVariableConfig = clusterHaGetGroupsRequestConfig()

        return request<Unit, ClusterHaGetGroupsResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clusterHaGetGroups
     *
     * @return RequestConfig
     */
    fun clusterHaGetGroupsRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/cluster/ha/groups",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /cluster/ha
     * Directory index
     * Directory index.
     * @return ClusterHaGetHaResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clusterHaGetHa() : ClusterHaGetHaResponse {
        val localVarResponse = clusterHaGetHaWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClusterHaGetHaResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /cluster/ha
     * Directory index
     * Directory index.
     * @return ApiResponse<ClusterHaGetHaResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clusterHaGetHaWithHttpInfo() : ApiResponse<ClusterHaGetHaResponse?> {
        val localVariableConfig = clusterHaGetHaRequestConfig()

        return request<Unit, ClusterHaGetHaResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clusterHaGetHa
     *
     * @return RequestConfig
     */
    fun clusterHaGetHaRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/cluster/ha",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /cluster/ha/resources
     * List HA resources
     * List HA resources.
     * @param type Only list resources of specific type (optional)
     * @return ClusterHaGetResourcesResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clusterHaGetResources(type: PveClusterHaTypeTypeEnum? = null) : ClusterHaGetResourcesResponse {
        val localVarResponse = clusterHaGetResourcesWithHttpInfo(type = type)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClusterHaGetResourcesResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /cluster/ha/resources
     * List HA resources
     * List HA resources.
     * @param type Only list resources of specific type (optional)
     * @return ApiResponse<ClusterHaGetResourcesResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clusterHaGetResourcesWithHttpInfo(type: PveClusterHaTypeTypeEnum?) : ApiResponse<ClusterHaGetResourcesResponse?> {
        val localVariableConfig = clusterHaGetResourcesRequestConfig(type = type)

        return request<Unit, ClusterHaGetResourcesResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clusterHaGetResources
     *
     * @param type Only list resources of specific type (optional)
     * @return RequestConfig
     */
    fun clusterHaGetResourcesRequestConfig(type: PveClusterHaTypeTypeEnum?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (type != null) {
                    put("type", listOf(type.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/cluster/ha/resources",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /cluster/ha/rules
     * Get HA rules
     * Get HA rules.
     * @param resource Limit the returned list to rules affecting the specified resource. (optional)
     * @param type Limit the returned list to the specified rule type. (optional)
     * @return ClusterHaGetRulesResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clusterHaGetRules(resource: kotlin.String? = null, type: PveClusterHaTypeTypeEnum2? = null) : ClusterHaGetRulesResponse {
        val localVarResponse = clusterHaGetRulesWithHttpInfo(resource = resource, type = type)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClusterHaGetRulesResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /cluster/ha/rules
     * Get HA rules
     * Get HA rules.
     * @param resource Limit the returned list to rules affecting the specified resource. (optional)
     * @param type Limit the returned list to the specified rule type. (optional)
     * @return ApiResponse<ClusterHaGetRulesResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clusterHaGetRulesWithHttpInfo(resource: kotlin.String?, type: PveClusterHaTypeTypeEnum2?) : ApiResponse<ClusterHaGetRulesResponse?> {
        val localVariableConfig = clusterHaGetRulesRequestConfig(resource = resource, type = type)

        return request<Unit, ClusterHaGetRulesResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clusterHaGetRules
     *
     * @param resource Limit the returned list to rules affecting the specified resource. (optional)
     * @param type Limit the returned list to the specified rule type. (optional)
     * @return RequestConfig
     */
    fun clusterHaGetRulesRequestConfig(resource: kotlin.String?, type: PveClusterHaTypeTypeEnum2?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (resource != null) {
                    put("resource", listOf(resource.toString()))
                }
                if (type != null) {
                    put("type", listOf(type.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/cluster/ha/rules",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /cluster/ha/status
     * Directory index
     * Directory index.
     * @return ClusterHaGetStatusResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clusterHaGetStatus() : ClusterHaGetStatusResponse {
        val localVarResponse = clusterHaGetStatusWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClusterHaGetStatusResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /cluster/ha/status
     * Directory index
     * Directory index.
     * @return ApiResponse<ClusterHaGetStatusResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clusterHaGetStatusWithHttpInfo() : ApiResponse<ClusterHaGetStatusResponse?> {
        val localVariableConfig = clusterHaGetStatusRequestConfig()

        return request<Unit, ClusterHaGetStatusResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clusterHaGetStatus
     *
     * @return RequestConfig
     */
    fun clusterHaGetStatusRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/cluster/ha/status",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /cluster/ha/status/manager_status
     * Get full HA manger status, including LRM status
     * Get full HA manger status, including LRM status.
     * @return ClusterHaManagerStatusResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clusterHaManagerStatus() : ClusterHaManagerStatusResponse {
        val localVarResponse = clusterHaManagerStatusWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClusterHaManagerStatusResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /cluster/ha/status/manager_status
     * Get full HA manger status, including LRM status
     * Get full HA manger status, including LRM status.
     * @return ApiResponse<ClusterHaManagerStatusResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clusterHaManagerStatusWithHttpInfo() : ApiResponse<ClusterHaManagerStatusResponse?> {
        val localVariableConfig = clusterHaManagerStatusRequestConfig()

        return request<Unit, ClusterHaManagerStatusResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clusterHaManagerStatus
     *
     * @return RequestConfig
     */
    fun clusterHaManagerStatusRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/cluster/ha/status/manager_status",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /cluster/ha/resources/{sid}/migrate
     * Request resource migration (online) to another node
     * Request resource migration (online) to another node.
     * @param sid HA resource ID. This consists of a resource type followed by a resource specific name, separated with colon (example: vm:100 / ct:100). For virtual machines and containers, you can simply use the VM or CT id as a shortcut (example: 100).
     * @param clusterHaMigrateRequest 
     * @return ClusterHaMigrateResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clusterHaMigrate(sid: kotlin.String, clusterHaMigrateRequest: ClusterHaMigrateRequest) : ClusterHaMigrateResponse {
        val localVarResponse = clusterHaMigrateWithHttpInfo(sid = sid, clusterHaMigrateRequest = clusterHaMigrateRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClusterHaMigrateResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /cluster/ha/resources/{sid}/migrate
     * Request resource migration (online) to another node
     * Request resource migration (online) to another node.
     * @param sid HA resource ID. This consists of a resource type followed by a resource specific name, separated with colon (example: vm:100 / ct:100). For virtual machines and containers, you can simply use the VM or CT id as a shortcut (example: 100).
     * @param clusterHaMigrateRequest 
     * @return ApiResponse<ClusterHaMigrateResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clusterHaMigrateWithHttpInfo(sid: kotlin.String, clusterHaMigrateRequest: ClusterHaMigrateRequest) : ApiResponse<ClusterHaMigrateResponse?> {
        val localVariableConfig = clusterHaMigrateRequestConfig(sid = sid, clusterHaMigrateRequest = clusterHaMigrateRequest)

        return request<ClusterHaMigrateRequest, ClusterHaMigrateResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clusterHaMigrate
     *
     * @param sid HA resource ID. This consists of a resource type followed by a resource specific name, separated with colon (example: vm:100 / ct:100). For virtual machines and containers, you can simply use the VM or CT id as a shortcut (example: 100).
     * @param clusterHaMigrateRequest 
     * @return RequestConfig
     */
    fun clusterHaMigrateRequestConfig(sid: kotlin.String, clusterHaMigrateRequest: ClusterHaMigrateRequest) : RequestConfig<ClusterHaMigrateRequest> {
        val localVariableBody = clusterHaMigrateRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/cluster/ha/resources/{sid}/migrate".replace("{"+"sid"+"}", encodeURIComponent(sid.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /cluster/ha/groups/{group}
     * Read ha group configuration
     * Read ha group configuration. (deprecated in favor of HA rules)
     * @param group The HA group identifier.
     * @return ClusterHaReadGetGroupsResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clusterHaReadGetGroups(group: kotlin.String) : ClusterHaReadGetGroupsResponse {
        val localVarResponse = clusterHaReadGetGroupsWithHttpInfo(group = group)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClusterHaReadGetGroupsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /cluster/ha/groups/{group}
     * Read ha group configuration
     * Read ha group configuration. (deprecated in favor of HA rules)
     * @param group The HA group identifier.
     * @return ApiResponse<ClusterHaReadGetGroupsResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clusterHaReadGetGroupsWithHttpInfo(group: kotlin.String) : ApiResponse<ClusterHaReadGetGroupsResponse?> {
        val localVariableConfig = clusterHaReadGetGroupsRequestConfig(group = group)

        return request<Unit, ClusterHaReadGetGroupsResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clusterHaReadGetGroups
     *
     * @param group The HA group identifier.
     * @return RequestConfig
     */
    fun clusterHaReadGetGroupsRequestConfig(group: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/cluster/ha/groups/{group}".replace("{"+"group"+"}", encodeURIComponent(group.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /cluster/ha/resources/{sid}
     * Read resource configuration
     * Read resource configuration.
     * @param sid HA resource ID. This consists of a resource type followed by a resource specific name, separated with colon (example: vm:100 / ct:100). For virtual machines and containers, you can simply use the VM or CT id as a shortcut (example: 100).
     * @return ClusterHaReadGetResourcesResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clusterHaReadGetResources(sid: kotlin.String) : ClusterHaReadGetResourcesResponse {
        val localVarResponse = clusterHaReadGetResourcesWithHttpInfo(sid = sid)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClusterHaReadGetResourcesResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /cluster/ha/resources/{sid}
     * Read resource configuration
     * Read resource configuration.
     * @param sid HA resource ID. This consists of a resource type followed by a resource specific name, separated with colon (example: vm:100 / ct:100). For virtual machines and containers, you can simply use the VM or CT id as a shortcut (example: 100).
     * @return ApiResponse<ClusterHaReadGetResourcesResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clusterHaReadGetResourcesWithHttpInfo(sid: kotlin.String) : ApiResponse<ClusterHaReadGetResourcesResponse?> {
        val localVariableConfig = clusterHaReadGetResourcesRequestConfig(sid = sid)

        return request<Unit, ClusterHaReadGetResourcesResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clusterHaReadGetResources
     *
     * @param sid HA resource ID. This consists of a resource type followed by a resource specific name, separated with colon (example: vm:100 / ct:100). For virtual machines and containers, you can simply use the VM or CT id as a shortcut (example: 100).
     * @return RequestConfig
     */
    fun clusterHaReadGetResourcesRequestConfig(sid: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/cluster/ha/resources/{sid}".replace("{"+"sid"+"}", encodeURIComponent(sid.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /cluster/ha/rules/{rule}
     * Read HA rule
     * Read HA rule.
     * @param rule HA rule identifier.
     * @return ClusterHaReadRuleResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clusterHaReadRule(rule: kotlin.String) : ClusterHaReadRuleResponse {
        val localVarResponse = clusterHaReadRuleWithHttpInfo(rule = rule)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClusterHaReadRuleResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /cluster/ha/rules/{rule}
     * Read HA rule
     * Read HA rule.
     * @param rule HA rule identifier.
     * @return ApiResponse<ClusterHaReadRuleResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clusterHaReadRuleWithHttpInfo(rule: kotlin.String) : ApiResponse<ClusterHaReadRuleResponse?> {
        val localVariableConfig = clusterHaReadRuleRequestConfig(rule = rule)

        return request<Unit, ClusterHaReadRuleResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clusterHaReadRule
     *
     * @param rule HA rule identifier.
     * @return RequestConfig
     */
    fun clusterHaReadRuleRequestConfig(rule: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/cluster/ha/rules/{rule}".replace("{"+"rule"+"}", encodeURIComponent(rule.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /cluster/ha/resources/{sid}/relocate
     * Request resource relocatzion to another node
     * Request resource relocatzion to another node. This stops the service on the old node, and restarts it on the target node.
     * @param sid HA resource ID. This consists of a resource type followed by a resource specific name, separated with colon (example: vm:100 / ct:100). For virtual machines and containers, you can simply use the VM or CT id as a shortcut (example: 100).
     * @param clusterHaMigrateRequest 
     * @return ClusterHaRelocateResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clusterHaRelocate(sid: kotlin.String, clusterHaMigrateRequest: ClusterHaMigrateRequest) : ClusterHaRelocateResponse {
        val localVarResponse = clusterHaRelocateWithHttpInfo(sid = sid, clusterHaMigrateRequest = clusterHaMigrateRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClusterHaRelocateResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /cluster/ha/resources/{sid}/relocate
     * Request resource relocatzion to another node
     * Request resource relocatzion to another node. This stops the service on the old node, and restarts it on the target node.
     * @param sid HA resource ID. This consists of a resource type followed by a resource specific name, separated with colon (example: vm:100 / ct:100). For virtual machines and containers, you can simply use the VM or CT id as a shortcut (example: 100).
     * @param clusterHaMigrateRequest 
     * @return ApiResponse<ClusterHaRelocateResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clusterHaRelocateWithHttpInfo(sid: kotlin.String, clusterHaMigrateRequest: ClusterHaMigrateRequest) : ApiResponse<ClusterHaRelocateResponse?> {
        val localVariableConfig = clusterHaRelocateRequestConfig(sid = sid, clusterHaMigrateRequest = clusterHaMigrateRequest)

        return request<ClusterHaMigrateRequest, ClusterHaRelocateResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clusterHaRelocate
     *
     * @param sid HA resource ID. This consists of a resource type followed by a resource specific name, separated with colon (example: vm:100 / ct:100). For virtual machines and containers, you can simply use the VM or CT id as a shortcut (example: 100).
     * @param clusterHaMigrateRequest 
     * @return RequestConfig
     */
    fun clusterHaRelocateRequestConfig(sid: kotlin.String, clusterHaMigrateRequest: ClusterHaMigrateRequest) : RequestConfig<ClusterHaMigrateRequest> {
        val localVariableBody = clusterHaMigrateRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/cluster/ha/resources/{sid}/relocate".replace("{"+"sid"+"}", encodeURIComponent(sid.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /cluster/ha/status/current
     * Get HA manger status
     * Get HA manger status.
     * @return ClusterHaStatusResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clusterHaStatus() : ClusterHaStatusResponse {
        val localVarResponse = clusterHaStatusWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClusterHaStatusResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /cluster/ha/status/current
     * Get HA manger status
     * Get HA manger status.
     * @return ApiResponse<ClusterHaStatusResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clusterHaStatusWithHttpInfo() : ApiResponse<ClusterHaStatusResponse?> {
        val localVariableConfig = clusterHaStatusRequestConfig()

        return request<Unit, ClusterHaStatusResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clusterHaStatus
     *
     * @return RequestConfig
     */
    fun clusterHaStatusRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/cluster/ha/status/current",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /cluster/ha/groups/{group}
     * Update ha group configuration
     * Update ha group configuration. (deprecated in favor of HA rules)
     * @param group The HA group identifier.
     * @param clusterHaUpdateGroupsRequest  (optional)
     * @return ClusterHaUpdateGroupsResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clusterHaUpdateGroups(group: kotlin.String, clusterHaUpdateGroupsRequest: ClusterHaUpdateGroupsRequest? = null) : ClusterHaUpdateGroupsResponse {
        val localVarResponse = clusterHaUpdateGroupsWithHttpInfo(group = group, clusterHaUpdateGroupsRequest = clusterHaUpdateGroupsRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClusterHaUpdateGroupsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /cluster/ha/groups/{group}
     * Update ha group configuration
     * Update ha group configuration. (deprecated in favor of HA rules)
     * @param group The HA group identifier.
     * @param clusterHaUpdateGroupsRequest  (optional)
     * @return ApiResponse<ClusterHaUpdateGroupsResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clusterHaUpdateGroupsWithHttpInfo(group: kotlin.String, clusterHaUpdateGroupsRequest: ClusterHaUpdateGroupsRequest?) : ApiResponse<ClusterHaUpdateGroupsResponse?> {
        val localVariableConfig = clusterHaUpdateGroupsRequestConfig(group = group, clusterHaUpdateGroupsRequest = clusterHaUpdateGroupsRequest)

        return request<ClusterHaUpdateGroupsRequest, ClusterHaUpdateGroupsResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clusterHaUpdateGroups
     *
     * @param group The HA group identifier.
     * @param clusterHaUpdateGroupsRequest  (optional)
     * @return RequestConfig
     */
    fun clusterHaUpdateGroupsRequestConfig(group: kotlin.String, clusterHaUpdateGroupsRequest: ClusterHaUpdateGroupsRequest?) : RequestConfig<ClusterHaUpdateGroupsRequest> {
        val localVariableBody = clusterHaUpdateGroupsRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/cluster/ha/groups/{group}".replace("{"+"group"+"}", encodeURIComponent(group.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /cluster/ha/resources/{sid}
     * Update resource configuration
     * Update resource configuration.
     * @param sid HA resource ID. This consists of a resource type followed by a resource specific name, separated with colon (example: vm:100 / ct:100). For virtual machines and containers, you can simply use the VM or CT id as a shortcut (example: 100).
     * @param clusterHaUpdateResourcesRequest  (optional)
     * @return ClusterHaUpdateResourcesResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clusterHaUpdateResources(sid: kotlin.String, clusterHaUpdateResourcesRequest: ClusterHaUpdateResourcesRequest? = null) : ClusterHaUpdateResourcesResponse {
        val localVarResponse = clusterHaUpdateResourcesWithHttpInfo(sid = sid, clusterHaUpdateResourcesRequest = clusterHaUpdateResourcesRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClusterHaUpdateResourcesResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /cluster/ha/resources/{sid}
     * Update resource configuration
     * Update resource configuration.
     * @param sid HA resource ID. This consists of a resource type followed by a resource specific name, separated with colon (example: vm:100 / ct:100). For virtual machines and containers, you can simply use the VM or CT id as a shortcut (example: 100).
     * @param clusterHaUpdateResourcesRequest  (optional)
     * @return ApiResponse<ClusterHaUpdateResourcesResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clusterHaUpdateResourcesWithHttpInfo(sid: kotlin.String, clusterHaUpdateResourcesRequest: ClusterHaUpdateResourcesRequest?) : ApiResponse<ClusterHaUpdateResourcesResponse?> {
        val localVariableConfig = clusterHaUpdateResourcesRequestConfig(sid = sid, clusterHaUpdateResourcesRequest = clusterHaUpdateResourcesRequest)

        return request<ClusterHaUpdateResourcesRequest, ClusterHaUpdateResourcesResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clusterHaUpdateResources
     *
     * @param sid HA resource ID. This consists of a resource type followed by a resource specific name, separated with colon (example: vm:100 / ct:100). For virtual machines and containers, you can simply use the VM or CT id as a shortcut (example: 100).
     * @param clusterHaUpdateResourcesRequest  (optional)
     * @return RequestConfig
     */
    fun clusterHaUpdateResourcesRequestConfig(sid: kotlin.String, clusterHaUpdateResourcesRequest: ClusterHaUpdateResourcesRequest?) : RequestConfig<ClusterHaUpdateResourcesRequest> {
        val localVariableBody = clusterHaUpdateResourcesRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/cluster/ha/resources/{sid}".replace("{"+"sid"+"}", encodeURIComponent(sid.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /cluster/ha/rules/{rule}
     * Update HA rule
     * Update HA rule.
     * @param rule HA rule identifier.
     * @param clusterHaUpdateRuleRequest 
     * @return ClusterHaUpdateRuleResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clusterHaUpdateRule(rule: kotlin.String, clusterHaUpdateRuleRequest: ClusterHaUpdateRuleRequest) : ClusterHaUpdateRuleResponse {
        val localVarResponse = clusterHaUpdateRuleWithHttpInfo(rule = rule, clusterHaUpdateRuleRequest = clusterHaUpdateRuleRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClusterHaUpdateRuleResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /cluster/ha/rules/{rule}
     * Update HA rule
     * Update HA rule.
     * @param rule HA rule identifier.
     * @param clusterHaUpdateRuleRequest 
     * @return ApiResponse<ClusterHaUpdateRuleResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clusterHaUpdateRuleWithHttpInfo(rule: kotlin.String, clusterHaUpdateRuleRequest: ClusterHaUpdateRuleRequest) : ApiResponse<ClusterHaUpdateRuleResponse?> {
        val localVariableConfig = clusterHaUpdateRuleRequestConfig(rule = rule, clusterHaUpdateRuleRequest = clusterHaUpdateRuleRequest)

        return request<ClusterHaUpdateRuleRequest, ClusterHaUpdateRuleResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clusterHaUpdateRule
     *
     * @param rule HA rule identifier.
     * @param clusterHaUpdateRuleRequest 
     * @return RequestConfig
     */
    fun clusterHaUpdateRuleRequestConfig(rule: kotlin.String, clusterHaUpdateRuleRequest: ClusterHaUpdateRuleRequest) : RequestConfig<ClusterHaUpdateRuleRequest> {
        val localVariableBody = clusterHaUpdateRuleRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/cluster/ha/rules/{rule}".replace("{"+"rule"+"}", encodeURIComponent(rule.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
