/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import dev.clientapi.pve.models.ClusterMappingCreateDirRequest
import dev.clientapi.pve.models.ClusterMappingCreateDirResponse
import dev.clientapi.pve.models.ClusterMappingCreatePciRequest
import dev.clientapi.pve.models.ClusterMappingCreatePciResponse
import dev.clientapi.pve.models.ClusterMappingCreateUsbRequest
import dev.clientapi.pve.models.ClusterMappingCreateUsbResponse
import dev.clientapi.pve.models.ClusterMappingDeleteDirResponse
import dev.clientapi.pve.models.ClusterMappingDeletePciResponse
import dev.clientapi.pve.models.ClusterMappingDeleteUsbResponse
import dev.clientapi.pve.models.ClusterMappingGetDirResponse
import dev.clientapi.pve.models.ClusterMappingGetGetDirResponse
import dev.clientapi.pve.models.ClusterMappingGetGetPciResponse
import dev.clientapi.pve.models.ClusterMappingGetGetUsbResponse
import dev.clientapi.pve.models.ClusterMappingGetMappingResponse
import dev.clientapi.pve.models.ClusterMappingGetPciResponse
import dev.clientapi.pve.models.ClusterMappingGetUsbResponse
import dev.clientapi.pve.models.ClusterMappingUpdateDirRequest
import dev.clientapi.pve.models.ClusterMappingUpdateDirResponse
import dev.clientapi.pve.models.ClusterMappingUpdatePciRequest
import dev.clientapi.pve.models.ClusterMappingUpdatePciResponse
import dev.clientapi.pve.models.ClusterMappingUpdateUsbRequest
import dev.clientapi.pve.models.ClusterMappingUpdateUsbResponse
import dev.clientapi.pve.models.PveError

import com.squareup.moshi.Json

import dev.clientapi.pve.infrastructure.ApiClient
import dev.clientapi.pve.infrastructure.ApiResponse
import dev.clientapi.pve.infrastructure.ClientException
import dev.clientapi.pve.infrastructure.ClientError
import dev.clientapi.pve.infrastructure.ServerException
import dev.clientapi.pve.infrastructure.ServerError
import dev.clientapi.pve.infrastructure.MultiValueMap
import dev.clientapi.pve.infrastructure.PartConfig
import dev.clientapi.pve.infrastructure.RequestConfig
import dev.clientapi.pve.infrastructure.RequestMethod
import dev.clientapi.pve.infrastructure.ResponseType
import dev.clientapi.pve.infrastructure.Success
import dev.clientapi.pve.infrastructure.toMultiValue

open class ClusterMappingApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8006/api2/json")
        }
    }

    /**
     * POST /cluster/mapping/dir
     * Create a new directory mapping
     * Create a new directory mapping.
     * @param clusterMappingCreateDirRequest 
     * @return ClusterMappingCreateDirResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clusterMappingCreateDir(clusterMappingCreateDirRequest: ClusterMappingCreateDirRequest) : ClusterMappingCreateDirResponse {
        val localVarResponse = clusterMappingCreateDirWithHttpInfo(clusterMappingCreateDirRequest = clusterMappingCreateDirRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClusterMappingCreateDirResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /cluster/mapping/dir
     * Create a new directory mapping
     * Create a new directory mapping.
     * @param clusterMappingCreateDirRequest 
     * @return ApiResponse<ClusterMappingCreateDirResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clusterMappingCreateDirWithHttpInfo(clusterMappingCreateDirRequest: ClusterMappingCreateDirRequest) : ApiResponse<ClusterMappingCreateDirResponse?> {
        val localVariableConfig = clusterMappingCreateDirRequestConfig(clusterMappingCreateDirRequest = clusterMappingCreateDirRequest)

        return request<ClusterMappingCreateDirRequest, ClusterMappingCreateDirResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clusterMappingCreateDir
     *
     * @param clusterMappingCreateDirRequest 
     * @return RequestConfig
     */
    fun clusterMappingCreateDirRequestConfig(clusterMappingCreateDirRequest: ClusterMappingCreateDirRequest) : RequestConfig<ClusterMappingCreateDirRequest> {
        val localVariableBody = clusterMappingCreateDirRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/cluster/mapping/dir",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /cluster/mapping/pci
     * Create a new hardware mapping
     * Create a new hardware mapping.
     * @param clusterMappingCreatePciRequest 
     * @return ClusterMappingCreatePciResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clusterMappingCreatePci(clusterMappingCreatePciRequest: ClusterMappingCreatePciRequest) : ClusterMappingCreatePciResponse {
        val localVarResponse = clusterMappingCreatePciWithHttpInfo(clusterMappingCreatePciRequest = clusterMappingCreatePciRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClusterMappingCreatePciResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /cluster/mapping/pci
     * Create a new hardware mapping
     * Create a new hardware mapping.
     * @param clusterMappingCreatePciRequest 
     * @return ApiResponse<ClusterMappingCreatePciResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clusterMappingCreatePciWithHttpInfo(clusterMappingCreatePciRequest: ClusterMappingCreatePciRequest) : ApiResponse<ClusterMappingCreatePciResponse?> {
        val localVariableConfig = clusterMappingCreatePciRequestConfig(clusterMappingCreatePciRequest = clusterMappingCreatePciRequest)

        return request<ClusterMappingCreatePciRequest, ClusterMappingCreatePciResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clusterMappingCreatePci
     *
     * @param clusterMappingCreatePciRequest 
     * @return RequestConfig
     */
    fun clusterMappingCreatePciRequestConfig(clusterMappingCreatePciRequest: ClusterMappingCreatePciRequest) : RequestConfig<ClusterMappingCreatePciRequest> {
        val localVariableBody = clusterMappingCreatePciRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/cluster/mapping/pci",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /cluster/mapping/usb
     * Create a new hardware mapping
     * Create a new hardware mapping.
     * @param clusterMappingCreateUsbRequest 
     * @return ClusterMappingCreateUsbResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clusterMappingCreateUsb(clusterMappingCreateUsbRequest: ClusterMappingCreateUsbRequest) : ClusterMappingCreateUsbResponse {
        val localVarResponse = clusterMappingCreateUsbWithHttpInfo(clusterMappingCreateUsbRequest = clusterMappingCreateUsbRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClusterMappingCreateUsbResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /cluster/mapping/usb
     * Create a new hardware mapping
     * Create a new hardware mapping.
     * @param clusterMappingCreateUsbRequest 
     * @return ApiResponse<ClusterMappingCreateUsbResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clusterMappingCreateUsbWithHttpInfo(clusterMappingCreateUsbRequest: ClusterMappingCreateUsbRequest) : ApiResponse<ClusterMappingCreateUsbResponse?> {
        val localVariableConfig = clusterMappingCreateUsbRequestConfig(clusterMappingCreateUsbRequest = clusterMappingCreateUsbRequest)

        return request<ClusterMappingCreateUsbRequest, ClusterMappingCreateUsbResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clusterMappingCreateUsb
     *
     * @param clusterMappingCreateUsbRequest 
     * @return RequestConfig
     */
    fun clusterMappingCreateUsbRequestConfig(clusterMappingCreateUsbRequest: ClusterMappingCreateUsbRequest) : RequestConfig<ClusterMappingCreateUsbRequest> {
        val localVariableBody = clusterMappingCreateUsbRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/cluster/mapping/usb",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /cluster/mapping/dir/{id}
     * Remove directory mapping
     * Remove directory mapping.
     * @param id 
     * @return ClusterMappingDeleteDirResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clusterMappingDeleteDir(id: kotlin.String) : ClusterMappingDeleteDirResponse {
        val localVarResponse = clusterMappingDeleteDirWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClusterMappingDeleteDirResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /cluster/mapping/dir/{id}
     * Remove directory mapping
     * Remove directory mapping.
     * @param id 
     * @return ApiResponse<ClusterMappingDeleteDirResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clusterMappingDeleteDirWithHttpInfo(id: kotlin.String) : ApiResponse<ClusterMappingDeleteDirResponse?> {
        val localVariableConfig = clusterMappingDeleteDirRequestConfig(id = id)

        return request<Unit, ClusterMappingDeleteDirResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clusterMappingDeleteDir
     *
     * @param id 
     * @return RequestConfig
     */
    fun clusterMappingDeleteDirRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/cluster/mapping/dir/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /cluster/mapping/pci/{id}
     * Remove Hardware Mapping
     * Remove Hardware Mapping.
     * @param id 
     * @return ClusterMappingDeletePciResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clusterMappingDeletePci(id: kotlin.String) : ClusterMappingDeletePciResponse {
        val localVarResponse = clusterMappingDeletePciWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClusterMappingDeletePciResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /cluster/mapping/pci/{id}
     * Remove Hardware Mapping
     * Remove Hardware Mapping.
     * @param id 
     * @return ApiResponse<ClusterMappingDeletePciResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clusterMappingDeletePciWithHttpInfo(id: kotlin.String) : ApiResponse<ClusterMappingDeletePciResponse?> {
        val localVariableConfig = clusterMappingDeletePciRequestConfig(id = id)

        return request<Unit, ClusterMappingDeletePciResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clusterMappingDeletePci
     *
     * @param id 
     * @return RequestConfig
     */
    fun clusterMappingDeletePciRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/cluster/mapping/pci/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /cluster/mapping/usb/{id}
     * Remove Hardware Mapping
     * Remove Hardware Mapping.
     * @param id 
     * @return ClusterMappingDeleteUsbResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clusterMappingDeleteUsb(id: kotlin.String) : ClusterMappingDeleteUsbResponse {
        val localVarResponse = clusterMappingDeleteUsbWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClusterMappingDeleteUsbResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /cluster/mapping/usb/{id}
     * Remove Hardware Mapping
     * Remove Hardware Mapping.
     * @param id 
     * @return ApiResponse<ClusterMappingDeleteUsbResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clusterMappingDeleteUsbWithHttpInfo(id: kotlin.String) : ApiResponse<ClusterMappingDeleteUsbResponse?> {
        val localVariableConfig = clusterMappingDeleteUsbRequestConfig(id = id)

        return request<Unit, ClusterMappingDeleteUsbResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clusterMappingDeleteUsb
     *
     * @param id 
     * @return RequestConfig
     */
    fun clusterMappingDeleteUsbRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/cluster/mapping/usb/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /cluster/mapping/dir
     * List directory mapping
     * List directory mapping  Permissions: Only lists entries where you have &#39;Mapping.Modify&#39;, &#39;Mapping.Use&#39; or &#39;Mapping.Audit&#39; permissions on &#39;/mapping/dir/&lt;id&gt;&#39;.
     * @param checkNode If given, checks the configurations on the given node for correctness, and adds relevant diagnostics for the directory to the response. (optional)
     * @return ClusterMappingGetDirResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clusterMappingGetDir(checkNode: kotlin.String? = null) : ClusterMappingGetDirResponse {
        val localVarResponse = clusterMappingGetDirWithHttpInfo(checkNode = checkNode)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClusterMappingGetDirResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /cluster/mapping/dir
     * List directory mapping
     * List directory mapping  Permissions: Only lists entries where you have &#39;Mapping.Modify&#39;, &#39;Mapping.Use&#39; or &#39;Mapping.Audit&#39; permissions on &#39;/mapping/dir/&lt;id&gt;&#39;.
     * @param checkNode If given, checks the configurations on the given node for correctness, and adds relevant diagnostics for the directory to the response. (optional)
     * @return ApiResponse<ClusterMappingGetDirResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clusterMappingGetDirWithHttpInfo(checkNode: kotlin.String?) : ApiResponse<ClusterMappingGetDirResponse?> {
        val localVariableConfig = clusterMappingGetDirRequestConfig(checkNode = checkNode)

        return request<Unit, ClusterMappingGetDirResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clusterMappingGetDir
     *
     * @param checkNode If given, checks the configurations on the given node for correctness, and adds relevant diagnostics for the directory to the response. (optional)
     * @return RequestConfig
     */
    fun clusterMappingGetDirRequestConfig(checkNode: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (checkNode != null) {
                    put("check-node", listOf(checkNode.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/cluster/mapping/dir",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /cluster/mapping/dir/{id}
     * Get directory mapping
     * Get directory mapping.
     * @param id 
     * @return ClusterMappingGetGetDirResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clusterMappingGetGetDir(id: kotlin.String) : ClusterMappingGetGetDirResponse {
        val localVarResponse = clusterMappingGetGetDirWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClusterMappingGetGetDirResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /cluster/mapping/dir/{id}
     * Get directory mapping
     * Get directory mapping.
     * @param id 
     * @return ApiResponse<ClusterMappingGetGetDirResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clusterMappingGetGetDirWithHttpInfo(id: kotlin.String) : ApiResponse<ClusterMappingGetGetDirResponse?> {
        val localVariableConfig = clusterMappingGetGetDirRequestConfig(id = id)

        return request<Unit, ClusterMappingGetGetDirResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clusterMappingGetGetDir
     *
     * @param id 
     * @return RequestConfig
     */
    fun clusterMappingGetGetDirRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/cluster/mapping/dir/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /cluster/mapping/pci/{id}
     * Get PCI Mapping
     * Get PCI Mapping.
     * @param id 
     * @return ClusterMappingGetGetPciResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clusterMappingGetGetPci(id: kotlin.String) : ClusterMappingGetGetPciResponse {
        val localVarResponse = clusterMappingGetGetPciWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClusterMappingGetGetPciResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /cluster/mapping/pci/{id}
     * Get PCI Mapping
     * Get PCI Mapping.
     * @param id 
     * @return ApiResponse<ClusterMappingGetGetPciResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clusterMappingGetGetPciWithHttpInfo(id: kotlin.String) : ApiResponse<ClusterMappingGetGetPciResponse?> {
        val localVariableConfig = clusterMappingGetGetPciRequestConfig(id = id)

        return request<Unit, ClusterMappingGetGetPciResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clusterMappingGetGetPci
     *
     * @param id 
     * @return RequestConfig
     */
    fun clusterMappingGetGetPciRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/cluster/mapping/pci/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /cluster/mapping/usb/{id}
     * Get USB Mapping
     * Get USB Mapping.
     * @param id 
     * @return ClusterMappingGetGetUsbResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clusterMappingGetGetUsb(id: kotlin.String) : ClusterMappingGetGetUsbResponse {
        val localVarResponse = clusterMappingGetGetUsbWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClusterMappingGetGetUsbResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /cluster/mapping/usb/{id}
     * Get USB Mapping
     * Get USB Mapping.
     * @param id 
     * @return ApiResponse<ClusterMappingGetGetUsbResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clusterMappingGetGetUsbWithHttpInfo(id: kotlin.String) : ApiResponse<ClusterMappingGetGetUsbResponse?> {
        val localVariableConfig = clusterMappingGetGetUsbRequestConfig(id = id)

        return request<Unit, ClusterMappingGetGetUsbResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clusterMappingGetGetUsb
     *
     * @param id 
     * @return RequestConfig
     */
    fun clusterMappingGetGetUsbRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/cluster/mapping/usb/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /cluster/mapping
     * List resource types
     * List resource types.
     * @return ClusterMappingGetMappingResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clusterMappingGetMapping() : ClusterMappingGetMappingResponse {
        val localVarResponse = clusterMappingGetMappingWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClusterMappingGetMappingResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /cluster/mapping
     * List resource types
     * List resource types.
     * @return ApiResponse<ClusterMappingGetMappingResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clusterMappingGetMappingWithHttpInfo() : ApiResponse<ClusterMappingGetMappingResponse?> {
        val localVariableConfig = clusterMappingGetMappingRequestConfig()

        return request<Unit, ClusterMappingGetMappingResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clusterMappingGetMapping
     *
     * @return RequestConfig
     */
    fun clusterMappingGetMappingRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/cluster/mapping",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /cluster/mapping/pci
     * List PCI Hardware Mapping
     * List PCI Hardware Mapping  Permissions: Only lists entries where you have &#39;Mapping.Modify&#39;, &#39;Mapping.Use&#39; or &#39;Mapping.Audit&#39; permissions on &#39;/mapping/pci/&lt;id&gt;&#39;.
     * @param checkNode If given, checks the configurations on the given node for correctness, and adds relevant diagnostics for the devices to the response. (optional)
     * @return ClusterMappingGetPciResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clusterMappingGetPci(checkNode: kotlin.String? = null) : ClusterMappingGetPciResponse {
        val localVarResponse = clusterMappingGetPciWithHttpInfo(checkNode = checkNode)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClusterMappingGetPciResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /cluster/mapping/pci
     * List PCI Hardware Mapping
     * List PCI Hardware Mapping  Permissions: Only lists entries where you have &#39;Mapping.Modify&#39;, &#39;Mapping.Use&#39; or &#39;Mapping.Audit&#39; permissions on &#39;/mapping/pci/&lt;id&gt;&#39;.
     * @param checkNode If given, checks the configurations on the given node for correctness, and adds relevant diagnostics for the devices to the response. (optional)
     * @return ApiResponse<ClusterMappingGetPciResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clusterMappingGetPciWithHttpInfo(checkNode: kotlin.String?) : ApiResponse<ClusterMappingGetPciResponse?> {
        val localVariableConfig = clusterMappingGetPciRequestConfig(checkNode = checkNode)

        return request<Unit, ClusterMappingGetPciResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clusterMappingGetPci
     *
     * @param checkNode If given, checks the configurations on the given node for correctness, and adds relevant diagnostics for the devices to the response. (optional)
     * @return RequestConfig
     */
    fun clusterMappingGetPciRequestConfig(checkNode: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (checkNode != null) {
                    put("check-node", listOf(checkNode.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/cluster/mapping/pci",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /cluster/mapping/usb
     * List USB Hardware Mappings
     * List USB Hardware Mappings  Permissions: Only lists entries where you have &#39;Mapping.Modify&#39;, &#39;Mapping.Use&#39; or &#39;Mapping.Audit&#39; permissions on &#39;/mapping/usb/&lt;id&gt;&#39;.
     * @param checkNode If given, checks the configurations on the given node for correctness, and adds relevant errors to the devices. (optional)
     * @return ClusterMappingGetUsbResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clusterMappingGetUsb(checkNode: kotlin.String? = null) : ClusterMappingGetUsbResponse {
        val localVarResponse = clusterMappingGetUsbWithHttpInfo(checkNode = checkNode)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClusterMappingGetUsbResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /cluster/mapping/usb
     * List USB Hardware Mappings
     * List USB Hardware Mappings  Permissions: Only lists entries where you have &#39;Mapping.Modify&#39;, &#39;Mapping.Use&#39; or &#39;Mapping.Audit&#39; permissions on &#39;/mapping/usb/&lt;id&gt;&#39;.
     * @param checkNode If given, checks the configurations on the given node for correctness, and adds relevant errors to the devices. (optional)
     * @return ApiResponse<ClusterMappingGetUsbResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clusterMappingGetUsbWithHttpInfo(checkNode: kotlin.String?) : ApiResponse<ClusterMappingGetUsbResponse?> {
        val localVariableConfig = clusterMappingGetUsbRequestConfig(checkNode = checkNode)

        return request<Unit, ClusterMappingGetUsbResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clusterMappingGetUsb
     *
     * @param checkNode If given, checks the configurations on the given node for correctness, and adds relevant errors to the devices. (optional)
     * @return RequestConfig
     */
    fun clusterMappingGetUsbRequestConfig(checkNode: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (checkNode != null) {
                    put("check-node", listOf(checkNode.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/cluster/mapping/usb",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /cluster/mapping/dir/{id}
     * Update a directory mapping
     * Update a directory mapping.
     * @param id The ID of the directory mapping
     * @param clusterMappingUpdateDirRequest  (optional)
     * @return ClusterMappingUpdateDirResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clusterMappingUpdateDir(id: kotlin.String, clusterMappingUpdateDirRequest: ClusterMappingUpdateDirRequest? = null) : ClusterMappingUpdateDirResponse {
        val localVarResponse = clusterMappingUpdateDirWithHttpInfo(id = id, clusterMappingUpdateDirRequest = clusterMappingUpdateDirRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClusterMappingUpdateDirResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /cluster/mapping/dir/{id}
     * Update a directory mapping
     * Update a directory mapping.
     * @param id The ID of the directory mapping
     * @param clusterMappingUpdateDirRequest  (optional)
     * @return ApiResponse<ClusterMappingUpdateDirResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clusterMappingUpdateDirWithHttpInfo(id: kotlin.String, clusterMappingUpdateDirRequest: ClusterMappingUpdateDirRequest?) : ApiResponse<ClusterMappingUpdateDirResponse?> {
        val localVariableConfig = clusterMappingUpdateDirRequestConfig(id = id, clusterMappingUpdateDirRequest = clusterMappingUpdateDirRequest)

        return request<ClusterMappingUpdateDirRequest, ClusterMappingUpdateDirResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clusterMappingUpdateDir
     *
     * @param id The ID of the directory mapping
     * @param clusterMappingUpdateDirRequest  (optional)
     * @return RequestConfig
     */
    fun clusterMappingUpdateDirRequestConfig(id: kotlin.String, clusterMappingUpdateDirRequest: ClusterMappingUpdateDirRequest?) : RequestConfig<ClusterMappingUpdateDirRequest> {
        val localVariableBody = clusterMappingUpdateDirRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/cluster/mapping/dir/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /cluster/mapping/pci/{id}
     * Update a hardware mapping
     * Update a hardware mapping.
     * @param id The ID of the logical PCI mapping.
     * @param clusterMappingUpdatePciRequest  (optional)
     * @return ClusterMappingUpdatePciResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clusterMappingUpdatePci(id: kotlin.String, clusterMappingUpdatePciRequest: ClusterMappingUpdatePciRequest? = null) : ClusterMappingUpdatePciResponse {
        val localVarResponse = clusterMappingUpdatePciWithHttpInfo(id = id, clusterMappingUpdatePciRequest = clusterMappingUpdatePciRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClusterMappingUpdatePciResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /cluster/mapping/pci/{id}
     * Update a hardware mapping
     * Update a hardware mapping.
     * @param id The ID of the logical PCI mapping.
     * @param clusterMappingUpdatePciRequest  (optional)
     * @return ApiResponse<ClusterMappingUpdatePciResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clusterMappingUpdatePciWithHttpInfo(id: kotlin.String, clusterMappingUpdatePciRequest: ClusterMappingUpdatePciRequest?) : ApiResponse<ClusterMappingUpdatePciResponse?> {
        val localVariableConfig = clusterMappingUpdatePciRequestConfig(id = id, clusterMappingUpdatePciRequest = clusterMappingUpdatePciRequest)

        return request<ClusterMappingUpdatePciRequest, ClusterMappingUpdatePciResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clusterMappingUpdatePci
     *
     * @param id The ID of the logical PCI mapping.
     * @param clusterMappingUpdatePciRequest  (optional)
     * @return RequestConfig
     */
    fun clusterMappingUpdatePciRequestConfig(id: kotlin.String, clusterMappingUpdatePciRequest: ClusterMappingUpdatePciRequest?) : RequestConfig<ClusterMappingUpdatePciRequest> {
        val localVariableBody = clusterMappingUpdatePciRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/cluster/mapping/pci/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /cluster/mapping/usb/{id}
     * Update a hardware mapping
     * Update a hardware mapping.
     * @param id The ID of the logical USB mapping.
     * @param clusterMappingUpdateUsbRequest 
     * @return ClusterMappingUpdateUsbResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun clusterMappingUpdateUsb(id: kotlin.String, clusterMappingUpdateUsbRequest: ClusterMappingUpdateUsbRequest) : ClusterMappingUpdateUsbResponse {
        val localVarResponse = clusterMappingUpdateUsbWithHttpInfo(id = id, clusterMappingUpdateUsbRequest = clusterMappingUpdateUsbRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClusterMappingUpdateUsbResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /cluster/mapping/usb/{id}
     * Update a hardware mapping
     * Update a hardware mapping.
     * @param id The ID of the logical USB mapping.
     * @param clusterMappingUpdateUsbRequest 
     * @return ApiResponse<ClusterMappingUpdateUsbResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun clusterMappingUpdateUsbWithHttpInfo(id: kotlin.String, clusterMappingUpdateUsbRequest: ClusterMappingUpdateUsbRequest) : ApiResponse<ClusterMappingUpdateUsbResponse?> {
        val localVariableConfig = clusterMappingUpdateUsbRequestConfig(id = id, clusterMappingUpdateUsbRequest = clusterMappingUpdateUsbRequest)

        return request<ClusterMappingUpdateUsbRequest, ClusterMappingUpdateUsbResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation clusterMappingUpdateUsb
     *
     * @param id The ID of the logical USB mapping.
     * @param clusterMappingUpdateUsbRequest 
     * @return RequestConfig
     */
    fun clusterMappingUpdateUsbRequestConfig(id: kotlin.String, clusterMappingUpdateUsbRequest: ClusterMappingUpdateUsbRequest) : RequestConfig<ClusterMappingUpdateUsbRequest> {
        val localVariableBody = clusterMappingUpdateUsbRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/cluster/mapping/usb/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
