/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import dev.clientapi.pve.models.NodesAptAddRepositoryRequest
import dev.clientapi.pve.models.NodesAptAddRepositoryResponse
import dev.clientapi.pve.models.NodesAptChangeRepositoryRequest
import dev.clientapi.pve.models.NodesAptChangeRepositoryResponse
import dev.clientapi.pve.models.NodesAptChangelogResponse
import dev.clientapi.pve.models.NodesAptGetAptResponse
import dev.clientapi.pve.models.NodesAptListUpdatesResponse
import dev.clientapi.pve.models.NodesAptRepositoriesResponse
import dev.clientapi.pve.models.NodesAptUpdateDatabaseRequest
import dev.clientapi.pve.models.NodesAptUpdateDatabaseResponse
import dev.clientapi.pve.models.NodesAptVersionsResponse
import dev.clientapi.pve.models.PveError

import com.squareup.moshi.Json

import dev.clientapi.pve.infrastructure.ApiClient
import dev.clientapi.pve.infrastructure.ApiResponse
import dev.clientapi.pve.infrastructure.ClientException
import dev.clientapi.pve.infrastructure.ClientError
import dev.clientapi.pve.infrastructure.ServerException
import dev.clientapi.pve.infrastructure.ServerError
import dev.clientapi.pve.infrastructure.MultiValueMap
import dev.clientapi.pve.infrastructure.PartConfig
import dev.clientapi.pve.infrastructure.RequestConfig
import dev.clientapi.pve.infrastructure.RequestMethod
import dev.clientapi.pve.infrastructure.ResponseType
import dev.clientapi.pve.infrastructure.Success
import dev.clientapi.pve.infrastructure.toMultiValue

open class NodesAptApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8006/api2/json")
        }
    }

    /**
     * PUT /nodes/{node}/apt/repositories
     * Add a standard repository to the configuration
     * Add a standard repository to the configuration
     * @param node The cluster node name.
     * @param nodesAptAddRepositoryRequest 
     * @return NodesAptAddRepositoryResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesAptAddRepository(node: kotlin.String, nodesAptAddRepositoryRequest: NodesAptAddRepositoryRequest) : NodesAptAddRepositoryResponse {
        val localVarResponse = nodesAptAddRepositoryWithHttpInfo(node = node, nodesAptAddRepositoryRequest = nodesAptAddRepositoryRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesAptAddRepositoryResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /nodes/{node}/apt/repositories
     * Add a standard repository to the configuration
     * Add a standard repository to the configuration
     * @param node The cluster node name.
     * @param nodesAptAddRepositoryRequest 
     * @return ApiResponse<NodesAptAddRepositoryResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesAptAddRepositoryWithHttpInfo(node: kotlin.String, nodesAptAddRepositoryRequest: NodesAptAddRepositoryRequest) : ApiResponse<NodesAptAddRepositoryResponse?> {
        val localVariableConfig = nodesAptAddRepositoryRequestConfig(node = node, nodesAptAddRepositoryRequest = nodesAptAddRepositoryRequest)

        return request<NodesAptAddRepositoryRequest, NodesAptAddRepositoryResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesAptAddRepository
     *
     * @param node The cluster node name.
     * @param nodesAptAddRepositoryRequest 
     * @return RequestConfig
     */
    fun nodesAptAddRepositoryRequestConfig(node: kotlin.String, nodesAptAddRepositoryRequest: NodesAptAddRepositoryRequest) : RequestConfig<NodesAptAddRepositoryRequest> {
        val localVariableBody = nodesAptAddRepositoryRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/nodes/{node}/apt/repositories".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /nodes/{node}/apt/repositories
     * Change the properties of a repository
     * Change the properties of a repository. Currently only allows enabling/disabling.
     * @param node The cluster node name.
     * @param nodesAptChangeRepositoryRequest 
     * @return NodesAptChangeRepositoryResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesAptChangeRepository(node: kotlin.String, nodesAptChangeRepositoryRequest: NodesAptChangeRepositoryRequest) : NodesAptChangeRepositoryResponse {
        val localVarResponse = nodesAptChangeRepositoryWithHttpInfo(node = node, nodesAptChangeRepositoryRequest = nodesAptChangeRepositoryRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesAptChangeRepositoryResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /nodes/{node}/apt/repositories
     * Change the properties of a repository
     * Change the properties of a repository. Currently only allows enabling/disabling.
     * @param node The cluster node name.
     * @param nodesAptChangeRepositoryRequest 
     * @return ApiResponse<NodesAptChangeRepositoryResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesAptChangeRepositoryWithHttpInfo(node: kotlin.String, nodesAptChangeRepositoryRequest: NodesAptChangeRepositoryRequest) : ApiResponse<NodesAptChangeRepositoryResponse?> {
        val localVariableConfig = nodesAptChangeRepositoryRequestConfig(node = node, nodesAptChangeRepositoryRequest = nodesAptChangeRepositoryRequest)

        return request<NodesAptChangeRepositoryRequest, NodesAptChangeRepositoryResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesAptChangeRepository
     *
     * @param node The cluster node name.
     * @param nodesAptChangeRepositoryRequest 
     * @return RequestConfig
     */
    fun nodesAptChangeRepositoryRequestConfig(node: kotlin.String, nodesAptChangeRepositoryRequest: NodesAptChangeRepositoryRequest) : RequestConfig<NodesAptChangeRepositoryRequest> {
        val localVariableBody = nodesAptChangeRepositoryRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/nodes/{node}/apt/repositories".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /nodes/{node}/apt/changelog
     * Get package changelogs
     * Get package changelogs.
     * @param node The cluster node name.
     * @param name Package name.
     * @param version Package version. (optional)
     * @return NodesAptChangelogResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesAptChangelog(node: kotlin.String, name: kotlin.String, version: kotlin.String? = null) : NodesAptChangelogResponse {
        val localVarResponse = nodesAptChangelogWithHttpInfo(node = node, name = name, version = version)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesAptChangelogResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/apt/changelog
     * Get package changelogs
     * Get package changelogs.
     * @param node The cluster node name.
     * @param name Package name.
     * @param version Package version. (optional)
     * @return ApiResponse<NodesAptChangelogResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesAptChangelogWithHttpInfo(node: kotlin.String, name: kotlin.String, version: kotlin.String?) : ApiResponse<NodesAptChangelogResponse?> {
        val localVariableConfig = nodesAptChangelogRequestConfig(node = node, name = name, version = version)

        return request<Unit, NodesAptChangelogResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesAptChangelog
     *
     * @param node The cluster node name.
     * @param name Package name.
     * @param version Package version. (optional)
     * @return RequestConfig
     */
    fun nodesAptChangelogRequestConfig(node: kotlin.String, name: kotlin.String, version: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("name", listOf(name.toString()))
                if (version != null) {
                    put("version", listOf(version.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/apt/changelog".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /nodes/{node}/apt
     * Directory index for apt (Advanced Package Tool)
     * Directory index for apt (Advanced Package Tool).
     * @param node The cluster node name.
     * @return NodesAptGetAptResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesAptGetApt(node: kotlin.String) : NodesAptGetAptResponse {
        val localVarResponse = nodesAptGetAptWithHttpInfo(node = node)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesAptGetAptResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/apt
     * Directory index for apt (Advanced Package Tool)
     * Directory index for apt (Advanced Package Tool).
     * @param node The cluster node name.
     * @return ApiResponse<NodesAptGetAptResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesAptGetAptWithHttpInfo(node: kotlin.String) : ApiResponse<NodesAptGetAptResponse?> {
        val localVariableConfig = nodesAptGetAptRequestConfig(node = node)

        return request<Unit, NodesAptGetAptResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesAptGetApt
     *
     * @param node The cluster node name.
     * @return RequestConfig
     */
    fun nodesAptGetAptRequestConfig(node: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/apt".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /nodes/{node}/apt/update
     * List available updates
     * List available updates.
     * @param node The cluster node name.
     * @return NodesAptListUpdatesResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesAptListUpdates(node: kotlin.String) : NodesAptListUpdatesResponse {
        val localVarResponse = nodesAptListUpdatesWithHttpInfo(node = node)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesAptListUpdatesResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/apt/update
     * List available updates
     * List available updates.
     * @param node The cluster node name.
     * @return ApiResponse<NodesAptListUpdatesResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesAptListUpdatesWithHttpInfo(node: kotlin.String) : ApiResponse<NodesAptListUpdatesResponse?> {
        val localVariableConfig = nodesAptListUpdatesRequestConfig(node = node)

        return request<Unit, NodesAptListUpdatesResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesAptListUpdates
     *
     * @param node The cluster node name.
     * @return RequestConfig
     */
    fun nodesAptListUpdatesRequestConfig(node: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/apt/update".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /nodes/{node}/apt/repositories
     * Get APT repository information
     * Get APT repository information.
     * @param node The cluster node name.
     * @return NodesAptRepositoriesResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesAptRepositories(node: kotlin.String) : NodesAptRepositoriesResponse {
        val localVarResponse = nodesAptRepositoriesWithHttpInfo(node = node)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesAptRepositoriesResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/apt/repositories
     * Get APT repository information
     * Get APT repository information.
     * @param node The cluster node name.
     * @return ApiResponse<NodesAptRepositoriesResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesAptRepositoriesWithHttpInfo(node: kotlin.String) : ApiResponse<NodesAptRepositoriesResponse?> {
        val localVariableConfig = nodesAptRepositoriesRequestConfig(node = node)

        return request<Unit, NodesAptRepositoriesResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesAptRepositories
     *
     * @param node The cluster node name.
     * @return RequestConfig
     */
    fun nodesAptRepositoriesRequestConfig(node: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/apt/repositories".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /nodes/{node}/apt/update
     * This is used to resynchronize the package index files from their sources (apt-get update)
     * This is used to resynchronize the package index files from their sources (apt-get update).
     * @param node The cluster node name.
     * @param nodesAptUpdateDatabaseRequest  (optional)
     * @return NodesAptUpdateDatabaseResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesAptUpdateDatabase(node: kotlin.String, nodesAptUpdateDatabaseRequest: NodesAptUpdateDatabaseRequest? = null) : NodesAptUpdateDatabaseResponse {
        val localVarResponse = nodesAptUpdateDatabaseWithHttpInfo(node = node, nodesAptUpdateDatabaseRequest = nodesAptUpdateDatabaseRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesAptUpdateDatabaseResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /nodes/{node}/apt/update
     * This is used to resynchronize the package index files from their sources (apt-get update)
     * This is used to resynchronize the package index files from their sources (apt-get update).
     * @param node The cluster node name.
     * @param nodesAptUpdateDatabaseRequest  (optional)
     * @return ApiResponse<NodesAptUpdateDatabaseResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesAptUpdateDatabaseWithHttpInfo(node: kotlin.String, nodesAptUpdateDatabaseRequest: NodesAptUpdateDatabaseRequest?) : ApiResponse<NodesAptUpdateDatabaseResponse?> {
        val localVariableConfig = nodesAptUpdateDatabaseRequestConfig(node = node, nodesAptUpdateDatabaseRequest = nodesAptUpdateDatabaseRequest)

        return request<NodesAptUpdateDatabaseRequest, NodesAptUpdateDatabaseResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesAptUpdateDatabase
     *
     * @param node The cluster node name.
     * @param nodesAptUpdateDatabaseRequest  (optional)
     * @return RequestConfig
     */
    fun nodesAptUpdateDatabaseRequestConfig(node: kotlin.String, nodesAptUpdateDatabaseRequest: NodesAptUpdateDatabaseRequest?) : RequestConfig<NodesAptUpdateDatabaseRequest> {
        val localVariableBody = nodesAptUpdateDatabaseRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/nodes/{node}/apt/update".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /nodes/{node}/apt/versions
     * Get package information for important Proxmox packages
     * Get package information for important Proxmox packages.
     * @param node The cluster node name.
     * @return NodesAptVersionsResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesAptVersions(node: kotlin.String) : NodesAptVersionsResponse {
        val localVarResponse = nodesAptVersionsWithHttpInfo(node = node)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesAptVersionsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/apt/versions
     * Get package information for important Proxmox packages
     * Get package information for important Proxmox packages.
     * @param node The cluster node name.
     * @return ApiResponse<NodesAptVersionsResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesAptVersionsWithHttpInfo(node: kotlin.String) : ApiResponse<NodesAptVersionsResponse?> {
        val localVariableConfig = nodesAptVersionsRequestConfig(node = node)

        return request<Unit, NodesAptVersionsResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesAptVersions
     *
     * @param node The cluster node name.
     * @return RequestConfig
     */
    fun nodesAptVersionsRequestConfig(node: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/apt/versions".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
