/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import dev.clientapi.pve.models.NodesDisksCreateDirectoryRequest
import dev.clientapi.pve.models.NodesDisksCreateDirectoryResponse
import dev.clientapi.pve.models.NodesDisksCreateLvmRequest
import dev.clientapi.pve.models.NodesDisksCreateLvmResponse
import dev.clientapi.pve.models.NodesDisksCreateLvmthinRequest
import dev.clientapi.pve.models.NodesDisksCreateLvmthinResponse
import dev.clientapi.pve.models.NodesDisksCreateZfsRequest
import dev.clientapi.pve.models.NodesDisksCreateZfsResponse
import dev.clientapi.pve.models.NodesDisksDeleteDirectoryResponse
import dev.clientapi.pve.models.NodesDisksDeleteLvmResponse
import dev.clientapi.pve.models.NodesDisksDeleteLvmthinResponse
import dev.clientapi.pve.models.NodesDisksDeleteZfsResponse
import dev.clientapi.pve.models.NodesDisksDetailResponse
import dev.clientapi.pve.models.NodesDisksGetDirectoryResponse
import dev.clientapi.pve.models.NodesDisksGetDisksResponse
import dev.clientapi.pve.models.NodesDisksGetListResponse
import dev.clientapi.pve.models.NodesDisksGetLvmResponse
import dev.clientapi.pve.models.NodesDisksGetLvmthinResponse
import dev.clientapi.pve.models.NodesDisksGetZfsResponse
import dev.clientapi.pve.models.NodesDisksInitgptRequest
import dev.clientapi.pve.models.NodesDisksInitgptResponse
import dev.clientapi.pve.models.NodesDisksSmartResponse
import dev.clientapi.pve.models.NodesDisksWipeDiskRequest
import dev.clientapi.pve.models.NodesDisksWipeDiskResponse
import dev.clientapi.pve.models.PveBoolean
import dev.clientapi.pve.models.PveError
import dev.clientapi.pve.models.PveNodesDisksTypeEnum

import com.squareup.moshi.Json

import dev.clientapi.pve.infrastructure.ApiClient
import dev.clientapi.pve.infrastructure.ApiResponse
import dev.clientapi.pve.infrastructure.ClientException
import dev.clientapi.pve.infrastructure.ClientError
import dev.clientapi.pve.infrastructure.ServerException
import dev.clientapi.pve.infrastructure.ServerError
import dev.clientapi.pve.infrastructure.MultiValueMap
import dev.clientapi.pve.infrastructure.PartConfig
import dev.clientapi.pve.infrastructure.RequestConfig
import dev.clientapi.pve.infrastructure.RequestMethod
import dev.clientapi.pve.infrastructure.ResponseType
import dev.clientapi.pve.infrastructure.Success
import dev.clientapi.pve.infrastructure.toMultiValue

open class NodesDisksApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8006/api2/json")
        }
    }

    /**
     * POST /nodes/{node}/disks/directory
     * Create a Filesystem on an unused disk
     * Create a Filesystem on an unused disk. Will be mounted under &#39;/mnt/pve/NAME&#39;.  Permissions: Requires additionally &#39;Datastore.Allocate&#39; on /storage when setting &#39;add_storage&#39;
     * @param node The cluster node name.
     * @param nodesDisksCreateDirectoryRequest 
     * @return NodesDisksCreateDirectoryResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesDisksCreateDirectory(node: kotlin.String, nodesDisksCreateDirectoryRequest: NodesDisksCreateDirectoryRequest) : NodesDisksCreateDirectoryResponse {
        val localVarResponse = nodesDisksCreateDirectoryWithHttpInfo(node = node, nodesDisksCreateDirectoryRequest = nodesDisksCreateDirectoryRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesDisksCreateDirectoryResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /nodes/{node}/disks/directory
     * Create a Filesystem on an unused disk
     * Create a Filesystem on an unused disk. Will be mounted under &#39;/mnt/pve/NAME&#39;.  Permissions: Requires additionally &#39;Datastore.Allocate&#39; on /storage when setting &#39;add_storage&#39;
     * @param node The cluster node name.
     * @param nodesDisksCreateDirectoryRequest 
     * @return ApiResponse<NodesDisksCreateDirectoryResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesDisksCreateDirectoryWithHttpInfo(node: kotlin.String, nodesDisksCreateDirectoryRequest: NodesDisksCreateDirectoryRequest) : ApiResponse<NodesDisksCreateDirectoryResponse?> {
        val localVariableConfig = nodesDisksCreateDirectoryRequestConfig(node = node, nodesDisksCreateDirectoryRequest = nodesDisksCreateDirectoryRequest)

        return request<NodesDisksCreateDirectoryRequest, NodesDisksCreateDirectoryResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesDisksCreateDirectory
     *
     * @param node The cluster node name.
     * @param nodesDisksCreateDirectoryRequest 
     * @return RequestConfig
     */
    fun nodesDisksCreateDirectoryRequestConfig(node: kotlin.String, nodesDisksCreateDirectoryRequest: NodesDisksCreateDirectoryRequest) : RequestConfig<NodesDisksCreateDirectoryRequest> {
        val localVariableBody = nodesDisksCreateDirectoryRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/nodes/{node}/disks/directory".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /nodes/{node}/disks/lvm
     * Create an LVM Volume Group
     * Create an LVM Volume Group  Permissions: Requires additionally &#39;Datastore.Allocate&#39; on /storage when setting &#39;add_storage&#39;
     * @param node The cluster node name.
     * @param nodesDisksCreateLvmRequest 
     * @return NodesDisksCreateLvmResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesDisksCreateLvm(node: kotlin.String, nodesDisksCreateLvmRequest: NodesDisksCreateLvmRequest) : NodesDisksCreateLvmResponse {
        val localVarResponse = nodesDisksCreateLvmWithHttpInfo(node = node, nodesDisksCreateLvmRequest = nodesDisksCreateLvmRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesDisksCreateLvmResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /nodes/{node}/disks/lvm
     * Create an LVM Volume Group
     * Create an LVM Volume Group  Permissions: Requires additionally &#39;Datastore.Allocate&#39; on /storage when setting &#39;add_storage&#39;
     * @param node The cluster node name.
     * @param nodesDisksCreateLvmRequest 
     * @return ApiResponse<NodesDisksCreateLvmResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesDisksCreateLvmWithHttpInfo(node: kotlin.String, nodesDisksCreateLvmRequest: NodesDisksCreateLvmRequest) : ApiResponse<NodesDisksCreateLvmResponse?> {
        val localVariableConfig = nodesDisksCreateLvmRequestConfig(node = node, nodesDisksCreateLvmRequest = nodesDisksCreateLvmRequest)

        return request<NodesDisksCreateLvmRequest, NodesDisksCreateLvmResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesDisksCreateLvm
     *
     * @param node The cluster node name.
     * @param nodesDisksCreateLvmRequest 
     * @return RequestConfig
     */
    fun nodesDisksCreateLvmRequestConfig(node: kotlin.String, nodesDisksCreateLvmRequest: NodesDisksCreateLvmRequest) : RequestConfig<NodesDisksCreateLvmRequest> {
        val localVariableBody = nodesDisksCreateLvmRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/nodes/{node}/disks/lvm".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /nodes/{node}/disks/lvmthin
     * Create an LVM thinpool
     * Create an LVM thinpool  Permissions: Requires additionally &#39;Datastore.Allocate&#39; on /storage when setting &#39;add_storage&#39;
     * @param node The cluster node name.
     * @param nodesDisksCreateLvmthinRequest 
     * @return NodesDisksCreateLvmthinResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesDisksCreateLvmthin(node: kotlin.String, nodesDisksCreateLvmthinRequest: NodesDisksCreateLvmthinRequest) : NodesDisksCreateLvmthinResponse {
        val localVarResponse = nodesDisksCreateLvmthinWithHttpInfo(node = node, nodesDisksCreateLvmthinRequest = nodesDisksCreateLvmthinRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesDisksCreateLvmthinResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /nodes/{node}/disks/lvmthin
     * Create an LVM thinpool
     * Create an LVM thinpool  Permissions: Requires additionally &#39;Datastore.Allocate&#39; on /storage when setting &#39;add_storage&#39;
     * @param node The cluster node name.
     * @param nodesDisksCreateLvmthinRequest 
     * @return ApiResponse<NodesDisksCreateLvmthinResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesDisksCreateLvmthinWithHttpInfo(node: kotlin.String, nodesDisksCreateLvmthinRequest: NodesDisksCreateLvmthinRequest) : ApiResponse<NodesDisksCreateLvmthinResponse?> {
        val localVariableConfig = nodesDisksCreateLvmthinRequestConfig(node = node, nodesDisksCreateLvmthinRequest = nodesDisksCreateLvmthinRequest)

        return request<NodesDisksCreateLvmthinRequest, NodesDisksCreateLvmthinResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesDisksCreateLvmthin
     *
     * @param node The cluster node name.
     * @param nodesDisksCreateLvmthinRequest 
     * @return RequestConfig
     */
    fun nodesDisksCreateLvmthinRequestConfig(node: kotlin.String, nodesDisksCreateLvmthinRequest: NodesDisksCreateLvmthinRequest) : RequestConfig<NodesDisksCreateLvmthinRequest> {
        val localVariableBody = nodesDisksCreateLvmthinRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/nodes/{node}/disks/lvmthin".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /nodes/{node}/disks/zfs
     * Create a ZFS pool
     * Create a ZFS pool.  Permissions: Requires additionally &#39;Datastore.Allocate&#39; on /storage when setting &#39;add_storage&#39;
     * @param node The cluster node name.
     * @param nodesDisksCreateZfsRequest 
     * @return NodesDisksCreateZfsResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesDisksCreateZfs(node: kotlin.String, nodesDisksCreateZfsRequest: NodesDisksCreateZfsRequest) : NodesDisksCreateZfsResponse {
        val localVarResponse = nodesDisksCreateZfsWithHttpInfo(node = node, nodesDisksCreateZfsRequest = nodesDisksCreateZfsRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesDisksCreateZfsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /nodes/{node}/disks/zfs
     * Create a ZFS pool
     * Create a ZFS pool.  Permissions: Requires additionally &#39;Datastore.Allocate&#39; on /storage when setting &#39;add_storage&#39;
     * @param node The cluster node name.
     * @param nodesDisksCreateZfsRequest 
     * @return ApiResponse<NodesDisksCreateZfsResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesDisksCreateZfsWithHttpInfo(node: kotlin.String, nodesDisksCreateZfsRequest: NodesDisksCreateZfsRequest) : ApiResponse<NodesDisksCreateZfsResponse?> {
        val localVariableConfig = nodesDisksCreateZfsRequestConfig(node = node, nodesDisksCreateZfsRequest = nodesDisksCreateZfsRequest)

        return request<NodesDisksCreateZfsRequest, NodesDisksCreateZfsResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesDisksCreateZfs
     *
     * @param node The cluster node name.
     * @param nodesDisksCreateZfsRequest 
     * @return RequestConfig
     */
    fun nodesDisksCreateZfsRequestConfig(node: kotlin.String, nodesDisksCreateZfsRequest: NodesDisksCreateZfsRequest) : RequestConfig<NodesDisksCreateZfsRequest> {
        val localVariableBody = nodesDisksCreateZfsRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/nodes/{node}/disks/zfs".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /nodes/{node}/disks/directory/{name}
     * Unmounts the storage and removes the mount unit
     * Unmounts the storage and removes the mount unit.  Permissions: Requires additionally &#39;Datastore.Allocate&#39; on /storage when setting &#39;cleanup-config&#39;
     * @param name The storage identifier.
     * @param node The cluster node name.
     * @param cleanupConfig Marks associated storage(s) as not available on this node anymore or removes them from the configuration (if configured for this node only). (optional)
     * @param cleanupDisks Also wipe disk so it can be repurposed afterwards. (optional)
     * @return NodesDisksDeleteDirectoryResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesDisksDeleteDirectory(name: kotlin.String, node: kotlin.String, cleanupConfig: PveBoolean? = null, cleanupDisks: PveBoolean? = null) : NodesDisksDeleteDirectoryResponse {
        val localVarResponse = nodesDisksDeleteDirectoryWithHttpInfo(name = name, node = node, cleanupConfig = cleanupConfig, cleanupDisks = cleanupDisks)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesDisksDeleteDirectoryResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /nodes/{node}/disks/directory/{name}
     * Unmounts the storage and removes the mount unit
     * Unmounts the storage and removes the mount unit.  Permissions: Requires additionally &#39;Datastore.Allocate&#39; on /storage when setting &#39;cleanup-config&#39;
     * @param name The storage identifier.
     * @param node The cluster node name.
     * @param cleanupConfig Marks associated storage(s) as not available on this node anymore or removes them from the configuration (if configured for this node only). (optional)
     * @param cleanupDisks Also wipe disk so it can be repurposed afterwards. (optional)
     * @return ApiResponse<NodesDisksDeleteDirectoryResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesDisksDeleteDirectoryWithHttpInfo(name: kotlin.String, node: kotlin.String, cleanupConfig: PveBoolean?, cleanupDisks: PveBoolean?) : ApiResponse<NodesDisksDeleteDirectoryResponse?> {
        val localVariableConfig = nodesDisksDeleteDirectoryRequestConfig(name = name, node = node, cleanupConfig = cleanupConfig, cleanupDisks = cleanupDisks)

        return request<Unit, NodesDisksDeleteDirectoryResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesDisksDeleteDirectory
     *
     * @param name The storage identifier.
     * @param node The cluster node name.
     * @param cleanupConfig Marks associated storage(s) as not available on this node anymore or removes them from the configuration (if configured for this node only). (optional)
     * @param cleanupDisks Also wipe disk so it can be repurposed afterwards. (optional)
     * @return RequestConfig
     */
    fun nodesDisksDeleteDirectoryRequestConfig(name: kotlin.String, node: kotlin.String, cleanupConfig: PveBoolean?, cleanupDisks: PveBoolean?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (cleanupConfig != null) {
                    put("cleanup-config", listOf(cleanupConfig.toString()))
                }
                if (cleanupDisks != null) {
                    put("cleanup-disks", listOf(cleanupDisks.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/nodes/{node}/disks/directory/{name}".replace("{"+"name"+"}", encodeURIComponent(name.toString())).replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /nodes/{node}/disks/lvm/{name}
     * Remove an LVM Volume Group
     * Remove an LVM Volume Group.  Permissions: Requires additionally &#39;Datastore.Allocate&#39; on /storage when setting &#39;cleanup-config&#39;
     * @param name The storage identifier.
     * @param node The cluster node name.
     * @param cleanupConfig Marks associated storage(s) as not available on this node anymore or removes them from the configuration (if configured for this node only). (optional)
     * @param cleanupDisks Also wipe disks so they can be repurposed afterwards. (optional)
     * @return NodesDisksDeleteLvmResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesDisksDeleteLvm(name: kotlin.String, node: kotlin.String, cleanupConfig: PveBoolean? = null, cleanupDisks: PveBoolean? = null) : NodesDisksDeleteLvmResponse {
        val localVarResponse = nodesDisksDeleteLvmWithHttpInfo(name = name, node = node, cleanupConfig = cleanupConfig, cleanupDisks = cleanupDisks)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesDisksDeleteLvmResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /nodes/{node}/disks/lvm/{name}
     * Remove an LVM Volume Group
     * Remove an LVM Volume Group.  Permissions: Requires additionally &#39;Datastore.Allocate&#39; on /storage when setting &#39;cleanup-config&#39;
     * @param name The storage identifier.
     * @param node The cluster node name.
     * @param cleanupConfig Marks associated storage(s) as not available on this node anymore or removes them from the configuration (if configured for this node only). (optional)
     * @param cleanupDisks Also wipe disks so they can be repurposed afterwards. (optional)
     * @return ApiResponse<NodesDisksDeleteLvmResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesDisksDeleteLvmWithHttpInfo(name: kotlin.String, node: kotlin.String, cleanupConfig: PveBoolean?, cleanupDisks: PveBoolean?) : ApiResponse<NodesDisksDeleteLvmResponse?> {
        val localVariableConfig = nodesDisksDeleteLvmRequestConfig(name = name, node = node, cleanupConfig = cleanupConfig, cleanupDisks = cleanupDisks)

        return request<Unit, NodesDisksDeleteLvmResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesDisksDeleteLvm
     *
     * @param name The storage identifier.
     * @param node The cluster node name.
     * @param cleanupConfig Marks associated storage(s) as not available on this node anymore or removes them from the configuration (if configured for this node only). (optional)
     * @param cleanupDisks Also wipe disks so they can be repurposed afterwards. (optional)
     * @return RequestConfig
     */
    fun nodesDisksDeleteLvmRequestConfig(name: kotlin.String, node: kotlin.String, cleanupConfig: PveBoolean?, cleanupDisks: PveBoolean?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (cleanupConfig != null) {
                    put("cleanup-config", listOf(cleanupConfig.toString()))
                }
                if (cleanupDisks != null) {
                    put("cleanup-disks", listOf(cleanupDisks.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/nodes/{node}/disks/lvm/{name}".replace("{"+"name"+"}", encodeURIComponent(name.toString())).replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /nodes/{node}/disks/lvmthin/{name}
     * Remove an LVM thin pool
     * Remove an LVM thin pool.  Permissions: Requires additionally &#39;Datastore.Allocate&#39; on /storage when setting &#39;cleanup-config&#39;
     * @param name The storage identifier.
     * @param node The cluster node name.
     * @param volumeGroup The storage identifier.
     * @param cleanupConfig Marks associated storage(s) as not available on this node anymore or removes them from the configuration (if configured for this node only). (optional)
     * @param cleanupDisks Also wipe disks so they can be repurposed afterwards. (optional)
     * @return NodesDisksDeleteLvmthinResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesDisksDeleteLvmthin(name: kotlin.String, node: kotlin.String, volumeGroup: kotlin.String, cleanupConfig: PveBoolean? = null, cleanupDisks: PveBoolean? = null) : NodesDisksDeleteLvmthinResponse {
        val localVarResponse = nodesDisksDeleteLvmthinWithHttpInfo(name = name, node = node, volumeGroup = volumeGroup, cleanupConfig = cleanupConfig, cleanupDisks = cleanupDisks)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesDisksDeleteLvmthinResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /nodes/{node}/disks/lvmthin/{name}
     * Remove an LVM thin pool
     * Remove an LVM thin pool.  Permissions: Requires additionally &#39;Datastore.Allocate&#39; on /storage when setting &#39;cleanup-config&#39;
     * @param name The storage identifier.
     * @param node The cluster node name.
     * @param volumeGroup The storage identifier.
     * @param cleanupConfig Marks associated storage(s) as not available on this node anymore or removes them from the configuration (if configured for this node only). (optional)
     * @param cleanupDisks Also wipe disks so they can be repurposed afterwards. (optional)
     * @return ApiResponse<NodesDisksDeleteLvmthinResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesDisksDeleteLvmthinWithHttpInfo(name: kotlin.String, node: kotlin.String, volumeGroup: kotlin.String, cleanupConfig: PveBoolean?, cleanupDisks: PveBoolean?) : ApiResponse<NodesDisksDeleteLvmthinResponse?> {
        val localVariableConfig = nodesDisksDeleteLvmthinRequestConfig(name = name, node = node, volumeGroup = volumeGroup, cleanupConfig = cleanupConfig, cleanupDisks = cleanupDisks)

        return request<Unit, NodesDisksDeleteLvmthinResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesDisksDeleteLvmthin
     *
     * @param name The storage identifier.
     * @param node The cluster node name.
     * @param volumeGroup The storage identifier.
     * @param cleanupConfig Marks associated storage(s) as not available on this node anymore or removes them from the configuration (if configured for this node only). (optional)
     * @param cleanupDisks Also wipe disks so they can be repurposed afterwards. (optional)
     * @return RequestConfig
     */
    fun nodesDisksDeleteLvmthinRequestConfig(name: kotlin.String, node: kotlin.String, volumeGroup: kotlin.String, cleanupConfig: PveBoolean?, cleanupDisks: PveBoolean?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (cleanupConfig != null) {
                    put("cleanup-config", listOf(cleanupConfig.toString()))
                }
                if (cleanupDisks != null) {
                    put("cleanup-disks", listOf(cleanupDisks.toString()))
                }
                put("volume-group", listOf(volumeGroup.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/nodes/{node}/disks/lvmthin/{name}".replace("{"+"name"+"}", encodeURIComponent(name.toString())).replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /nodes/{node}/disks/zfs/{name}
     * Destroy a ZFS pool
     * Destroy a ZFS pool.  Permissions: Requires additionally &#39;Datastore.Allocate&#39; on /storage when setting &#39;cleanup-config&#39;
     * @param name The storage identifier.
     * @param node The cluster node name.
     * @param cleanupConfig Marks associated storage(s) as not available on this node anymore or removes them from the configuration (if configured for this node only). (optional)
     * @param cleanupDisks Also wipe disks so they can be repurposed afterwards. (optional)
     * @return NodesDisksDeleteZfsResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesDisksDeleteZfs(name: kotlin.String, node: kotlin.String, cleanupConfig: PveBoolean? = null, cleanupDisks: PveBoolean? = null) : NodesDisksDeleteZfsResponse {
        val localVarResponse = nodesDisksDeleteZfsWithHttpInfo(name = name, node = node, cleanupConfig = cleanupConfig, cleanupDisks = cleanupDisks)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesDisksDeleteZfsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /nodes/{node}/disks/zfs/{name}
     * Destroy a ZFS pool
     * Destroy a ZFS pool.  Permissions: Requires additionally &#39;Datastore.Allocate&#39; on /storage when setting &#39;cleanup-config&#39;
     * @param name The storage identifier.
     * @param node The cluster node name.
     * @param cleanupConfig Marks associated storage(s) as not available on this node anymore or removes them from the configuration (if configured for this node only). (optional)
     * @param cleanupDisks Also wipe disks so they can be repurposed afterwards. (optional)
     * @return ApiResponse<NodesDisksDeleteZfsResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesDisksDeleteZfsWithHttpInfo(name: kotlin.String, node: kotlin.String, cleanupConfig: PveBoolean?, cleanupDisks: PveBoolean?) : ApiResponse<NodesDisksDeleteZfsResponse?> {
        val localVariableConfig = nodesDisksDeleteZfsRequestConfig(name = name, node = node, cleanupConfig = cleanupConfig, cleanupDisks = cleanupDisks)

        return request<Unit, NodesDisksDeleteZfsResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesDisksDeleteZfs
     *
     * @param name The storage identifier.
     * @param node The cluster node name.
     * @param cleanupConfig Marks associated storage(s) as not available on this node anymore or removes them from the configuration (if configured for this node only). (optional)
     * @param cleanupDisks Also wipe disks so they can be repurposed afterwards. (optional)
     * @return RequestConfig
     */
    fun nodesDisksDeleteZfsRequestConfig(name: kotlin.String, node: kotlin.String, cleanupConfig: PveBoolean?, cleanupDisks: PveBoolean?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (cleanupConfig != null) {
                    put("cleanup-config", listOf(cleanupConfig.toString()))
                }
                if (cleanupDisks != null) {
                    put("cleanup-disks", listOf(cleanupDisks.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/nodes/{node}/disks/zfs/{name}".replace("{"+"name"+"}", encodeURIComponent(name.toString())).replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /nodes/{node}/disks/zfs/{name}
     * Get details about a zpool
     * Get details about a zpool.
     * @param name The storage identifier.
     * @param node The cluster node name.
     * @return NodesDisksDetailResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesDisksDetail(name: kotlin.String, node: kotlin.String) : NodesDisksDetailResponse {
        val localVarResponse = nodesDisksDetailWithHttpInfo(name = name, node = node)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesDisksDetailResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/disks/zfs/{name}
     * Get details about a zpool
     * Get details about a zpool.
     * @param name The storage identifier.
     * @param node The cluster node name.
     * @return ApiResponse<NodesDisksDetailResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesDisksDetailWithHttpInfo(name: kotlin.String, node: kotlin.String) : ApiResponse<NodesDisksDetailResponse?> {
        val localVariableConfig = nodesDisksDetailRequestConfig(name = name, node = node)

        return request<Unit, NodesDisksDetailResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesDisksDetail
     *
     * @param name The storage identifier.
     * @param node The cluster node name.
     * @return RequestConfig
     */
    fun nodesDisksDetailRequestConfig(name: kotlin.String, node: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/disks/zfs/{name}".replace("{"+"name"+"}", encodeURIComponent(name.toString())).replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /nodes/{node}/disks/directory
     * PVE Managed Directory storages
     * PVE Managed Directory storages.
     * @param node The cluster node name.
     * @return NodesDisksGetDirectoryResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesDisksGetDirectory(node: kotlin.String) : NodesDisksGetDirectoryResponse {
        val localVarResponse = nodesDisksGetDirectoryWithHttpInfo(node = node)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesDisksGetDirectoryResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/disks/directory
     * PVE Managed Directory storages
     * PVE Managed Directory storages.
     * @param node The cluster node name.
     * @return ApiResponse<NodesDisksGetDirectoryResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesDisksGetDirectoryWithHttpInfo(node: kotlin.String) : ApiResponse<NodesDisksGetDirectoryResponse?> {
        val localVariableConfig = nodesDisksGetDirectoryRequestConfig(node = node)

        return request<Unit, NodesDisksGetDirectoryResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesDisksGetDirectory
     *
     * @param node The cluster node name.
     * @return RequestConfig
     */
    fun nodesDisksGetDirectoryRequestConfig(node: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/disks/directory".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /nodes/{node}/disks
     * Node index
     * Node index.
     * @param node The cluster node name.
     * @return NodesDisksGetDisksResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesDisksGetDisks(node: kotlin.String) : NodesDisksGetDisksResponse {
        val localVarResponse = nodesDisksGetDisksWithHttpInfo(node = node)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesDisksGetDisksResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/disks
     * Node index
     * Node index.
     * @param node The cluster node name.
     * @return ApiResponse<NodesDisksGetDisksResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesDisksGetDisksWithHttpInfo(node: kotlin.String) : ApiResponse<NodesDisksGetDisksResponse?> {
        val localVariableConfig = nodesDisksGetDisksRequestConfig(node = node)

        return request<Unit, NodesDisksGetDisksResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesDisksGetDisks
     *
     * @param node The cluster node name.
     * @return RequestConfig
     */
    fun nodesDisksGetDisksRequestConfig(node: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/disks".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /nodes/{node}/disks/list
     * List local disks
     * List local disks.
     * @param node The cluster node name.
     * @param includePartitions Also include partitions. (optional)
     * @param skipsmart Skip smart checks. (optional)
     * @param type Only list specific types of disks. (optional)
     * @return NodesDisksGetListResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesDisksGetList(node: kotlin.String, includePartitions: PveBoolean? = null, skipsmart: PveBoolean? = null, type: PveNodesDisksTypeEnum? = null) : NodesDisksGetListResponse {
        val localVarResponse = nodesDisksGetListWithHttpInfo(node = node, includePartitions = includePartitions, skipsmart = skipsmart, type = type)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesDisksGetListResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/disks/list
     * List local disks
     * List local disks.
     * @param node The cluster node name.
     * @param includePartitions Also include partitions. (optional)
     * @param skipsmart Skip smart checks. (optional)
     * @param type Only list specific types of disks. (optional)
     * @return ApiResponse<NodesDisksGetListResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesDisksGetListWithHttpInfo(node: kotlin.String, includePartitions: PveBoolean?, skipsmart: PveBoolean?, type: PveNodesDisksTypeEnum?) : ApiResponse<NodesDisksGetListResponse?> {
        val localVariableConfig = nodesDisksGetListRequestConfig(node = node, includePartitions = includePartitions, skipsmart = skipsmart, type = type)

        return request<Unit, NodesDisksGetListResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesDisksGetList
     *
     * @param node The cluster node name.
     * @param includePartitions Also include partitions. (optional)
     * @param skipsmart Skip smart checks. (optional)
     * @param type Only list specific types of disks. (optional)
     * @return RequestConfig
     */
    fun nodesDisksGetListRequestConfig(node: kotlin.String, includePartitions: PveBoolean?, skipsmart: PveBoolean?, type: PveNodesDisksTypeEnum?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (includePartitions != null) {
                    put("include-partitions", listOf(includePartitions.toString()))
                }
                if (skipsmart != null) {
                    put("skipsmart", listOf(skipsmart.toString()))
                }
                if (type != null) {
                    put("type", listOf(type.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/disks/list".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /nodes/{node}/disks/lvm
     * List LVM Volume Groups
     * List LVM Volume Groups
     * @param node The cluster node name.
     * @return NodesDisksGetLvmResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesDisksGetLvm(node: kotlin.String) : NodesDisksGetLvmResponse {
        val localVarResponse = nodesDisksGetLvmWithHttpInfo(node = node)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesDisksGetLvmResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/disks/lvm
     * List LVM Volume Groups
     * List LVM Volume Groups
     * @param node The cluster node name.
     * @return ApiResponse<NodesDisksGetLvmResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesDisksGetLvmWithHttpInfo(node: kotlin.String) : ApiResponse<NodesDisksGetLvmResponse?> {
        val localVariableConfig = nodesDisksGetLvmRequestConfig(node = node)

        return request<Unit, NodesDisksGetLvmResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesDisksGetLvm
     *
     * @param node The cluster node name.
     * @return RequestConfig
     */
    fun nodesDisksGetLvmRequestConfig(node: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/disks/lvm".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /nodes/{node}/disks/lvmthin
     * List LVM thinpools
     * List LVM thinpools
     * @param node The cluster node name.
     * @return NodesDisksGetLvmthinResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesDisksGetLvmthin(node: kotlin.String) : NodesDisksGetLvmthinResponse {
        val localVarResponse = nodesDisksGetLvmthinWithHttpInfo(node = node)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesDisksGetLvmthinResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/disks/lvmthin
     * List LVM thinpools
     * List LVM thinpools
     * @param node The cluster node name.
     * @return ApiResponse<NodesDisksGetLvmthinResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesDisksGetLvmthinWithHttpInfo(node: kotlin.String) : ApiResponse<NodesDisksGetLvmthinResponse?> {
        val localVariableConfig = nodesDisksGetLvmthinRequestConfig(node = node)

        return request<Unit, NodesDisksGetLvmthinResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesDisksGetLvmthin
     *
     * @param node The cluster node name.
     * @return RequestConfig
     */
    fun nodesDisksGetLvmthinRequestConfig(node: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/disks/lvmthin".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /nodes/{node}/disks/zfs
     * List Zpools
     * List Zpools.
     * @param node The cluster node name.
     * @return NodesDisksGetZfsResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesDisksGetZfs(node: kotlin.String) : NodesDisksGetZfsResponse {
        val localVarResponse = nodesDisksGetZfsWithHttpInfo(node = node)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesDisksGetZfsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/disks/zfs
     * List Zpools
     * List Zpools.
     * @param node The cluster node name.
     * @return ApiResponse<NodesDisksGetZfsResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesDisksGetZfsWithHttpInfo(node: kotlin.String) : ApiResponse<NodesDisksGetZfsResponse?> {
        val localVariableConfig = nodesDisksGetZfsRequestConfig(node = node)

        return request<Unit, NodesDisksGetZfsResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesDisksGetZfs
     *
     * @param node The cluster node name.
     * @return RequestConfig
     */
    fun nodesDisksGetZfsRequestConfig(node: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/disks/zfs".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /nodes/{node}/disks/initgpt
     * Initialize Disk with GPT
     * Initialize Disk with GPT
     * @param node The cluster node name.
     * @param nodesDisksInitgptRequest 
     * @return NodesDisksInitgptResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesDisksInitgpt(node: kotlin.String, nodesDisksInitgptRequest: NodesDisksInitgptRequest) : NodesDisksInitgptResponse {
        val localVarResponse = nodesDisksInitgptWithHttpInfo(node = node, nodesDisksInitgptRequest = nodesDisksInitgptRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesDisksInitgptResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /nodes/{node}/disks/initgpt
     * Initialize Disk with GPT
     * Initialize Disk with GPT
     * @param node The cluster node name.
     * @param nodesDisksInitgptRequest 
     * @return ApiResponse<NodesDisksInitgptResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesDisksInitgptWithHttpInfo(node: kotlin.String, nodesDisksInitgptRequest: NodesDisksInitgptRequest) : ApiResponse<NodesDisksInitgptResponse?> {
        val localVariableConfig = nodesDisksInitgptRequestConfig(node = node, nodesDisksInitgptRequest = nodesDisksInitgptRequest)

        return request<NodesDisksInitgptRequest, NodesDisksInitgptResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesDisksInitgpt
     *
     * @param node The cluster node name.
     * @param nodesDisksInitgptRequest 
     * @return RequestConfig
     */
    fun nodesDisksInitgptRequestConfig(node: kotlin.String, nodesDisksInitgptRequest: NodesDisksInitgptRequest) : RequestConfig<NodesDisksInitgptRequest> {
        val localVariableBody = nodesDisksInitgptRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/nodes/{node}/disks/initgpt".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /nodes/{node}/disks/smart
     * Get SMART Health of a disk
     * Get SMART Health of a disk.
     * @param node The cluster node name.
     * @param disk Block device name
     * @param healthonly If true returns only the health status (optional)
     * @return NodesDisksSmartResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesDisksSmart(node: kotlin.String, disk: kotlin.String, healthonly: PveBoolean? = null) : NodesDisksSmartResponse {
        val localVarResponse = nodesDisksSmartWithHttpInfo(node = node, disk = disk, healthonly = healthonly)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesDisksSmartResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/disks/smart
     * Get SMART Health of a disk
     * Get SMART Health of a disk.
     * @param node The cluster node name.
     * @param disk Block device name
     * @param healthonly If true returns only the health status (optional)
     * @return ApiResponse<NodesDisksSmartResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesDisksSmartWithHttpInfo(node: kotlin.String, disk: kotlin.String, healthonly: PveBoolean?) : ApiResponse<NodesDisksSmartResponse?> {
        val localVariableConfig = nodesDisksSmartRequestConfig(node = node, disk = disk, healthonly = healthonly)

        return request<Unit, NodesDisksSmartResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesDisksSmart
     *
     * @param node The cluster node name.
     * @param disk Block device name
     * @param healthonly If true returns only the health status (optional)
     * @return RequestConfig
     */
    fun nodesDisksSmartRequestConfig(node: kotlin.String, disk: kotlin.String, healthonly: PveBoolean?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("disk", listOf(disk.toString()))
                if (healthonly != null) {
                    put("healthonly", listOf(healthonly.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/disks/smart".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /nodes/{node}/disks/wipedisk
     * Wipe a disk or partition
     * Wipe a disk or partition.
     * @param node The cluster node name.
     * @param nodesDisksWipeDiskRequest 
     * @return NodesDisksWipeDiskResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesDisksWipeDisk(node: kotlin.String, nodesDisksWipeDiskRequest: NodesDisksWipeDiskRequest) : NodesDisksWipeDiskResponse {
        val localVarResponse = nodesDisksWipeDiskWithHttpInfo(node = node, nodesDisksWipeDiskRequest = nodesDisksWipeDiskRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesDisksWipeDiskResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /nodes/{node}/disks/wipedisk
     * Wipe a disk or partition
     * Wipe a disk or partition.
     * @param node The cluster node name.
     * @param nodesDisksWipeDiskRequest 
     * @return ApiResponse<NodesDisksWipeDiskResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesDisksWipeDiskWithHttpInfo(node: kotlin.String, nodesDisksWipeDiskRequest: NodesDisksWipeDiskRequest) : ApiResponse<NodesDisksWipeDiskResponse?> {
        val localVariableConfig = nodesDisksWipeDiskRequestConfig(node = node, nodesDisksWipeDiskRequest = nodesDisksWipeDiskRequest)

        return request<NodesDisksWipeDiskRequest, NodesDisksWipeDiskResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesDisksWipeDisk
     *
     * @param node The cluster node name.
     * @param nodesDisksWipeDiskRequest 
     * @return RequestConfig
     */
    fun nodesDisksWipeDiskRequestConfig(node: kotlin.String, nodesDisksWipeDiskRequest: NodesDisksWipeDiskRequest) : RequestConfig<NodesDisksWipeDiskRequest> {
        val localVariableBody = nodesDisksWipeDiskRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/nodes/{node}/disks/wipedisk".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
