/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import dev.clientapi.pve.models.NodesVzdumpDefaultsResponse
import dev.clientapi.pve.models.NodesVzdumpExtractconfigResponse
import dev.clientapi.pve.models.NodesVzdumpVzdumpRequest
import dev.clientapi.pve.models.NodesVzdumpVzdumpResponse
import dev.clientapi.pve.models.PveError

import com.squareup.moshi.Json

import dev.clientapi.pve.infrastructure.ApiClient
import dev.clientapi.pve.infrastructure.ApiResponse
import dev.clientapi.pve.infrastructure.ClientException
import dev.clientapi.pve.infrastructure.ClientError
import dev.clientapi.pve.infrastructure.ServerException
import dev.clientapi.pve.infrastructure.ServerError
import dev.clientapi.pve.infrastructure.MultiValueMap
import dev.clientapi.pve.infrastructure.PartConfig
import dev.clientapi.pve.infrastructure.RequestConfig
import dev.clientapi.pve.infrastructure.RequestMethod
import dev.clientapi.pve.infrastructure.ResponseType
import dev.clientapi.pve.infrastructure.Success
import dev.clientapi.pve.infrastructure.toMultiValue

open class NodesVzdumpApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8006/api2/json")
        }
    }

    /**
     * GET /nodes/{node}/vzdump/defaults
     * Get the currently configured vzdump defaults
     * Get the currently configured vzdump defaults.  Permissions: The user needs &#39;Datastore.Audit&#39; or &#39;Datastore.AllocateSpace&#39; permissions for the specified storage (or default storage if none specified). Some properties are only returned when the user has &#39;Sys.Audit&#39; permissions for the node.
     * @param node The cluster node name.
     * @param storage The storage identifier. (optional)
     * @return NodesVzdumpDefaultsResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesVzdumpDefaults(node: kotlin.String, storage: kotlin.String? = null) : NodesVzdumpDefaultsResponse {
        val localVarResponse = nodesVzdumpDefaultsWithHttpInfo(node = node, storage = storage)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesVzdumpDefaultsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/vzdump/defaults
     * Get the currently configured vzdump defaults
     * Get the currently configured vzdump defaults.  Permissions: The user needs &#39;Datastore.Audit&#39; or &#39;Datastore.AllocateSpace&#39; permissions for the specified storage (or default storage if none specified). Some properties are only returned when the user has &#39;Sys.Audit&#39; permissions for the node.
     * @param node The cluster node name.
     * @param storage The storage identifier. (optional)
     * @return ApiResponse<NodesVzdumpDefaultsResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesVzdumpDefaultsWithHttpInfo(node: kotlin.String, storage: kotlin.String?) : ApiResponse<NodesVzdumpDefaultsResponse?> {
        val localVariableConfig = nodesVzdumpDefaultsRequestConfig(node = node, storage = storage)

        return request<Unit, NodesVzdumpDefaultsResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesVzdumpDefaults
     *
     * @param node The cluster node name.
     * @param storage The storage identifier. (optional)
     * @return RequestConfig
     */
    fun nodesVzdumpDefaultsRequestConfig(node: kotlin.String, storage: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (storage != null) {
                    put("storage", listOf(storage.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/vzdump/defaults".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /nodes/{node}/vzdump/extractconfig
     * Extract configuration from vzdump backup archive
     * Extract configuration from vzdump backup archive.  Permissions: The user needs &#39;VM.Backup&#39; permissions on the backed up guest ID, and &#39;Datastore.AllocateSpace&#39; on the backup storage.
     * @param node The cluster node name.
     * @param volume Volume identifier
     * @return NodesVzdumpExtractconfigResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesVzdumpExtractconfig(node: kotlin.String, volume: kotlin.String) : NodesVzdumpExtractconfigResponse {
        val localVarResponse = nodesVzdumpExtractconfigWithHttpInfo(node = node, volume = volume)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesVzdumpExtractconfigResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/vzdump/extractconfig
     * Extract configuration from vzdump backup archive
     * Extract configuration from vzdump backup archive.  Permissions: The user needs &#39;VM.Backup&#39; permissions on the backed up guest ID, and &#39;Datastore.AllocateSpace&#39; on the backup storage.
     * @param node The cluster node name.
     * @param volume Volume identifier
     * @return ApiResponse<NodesVzdumpExtractconfigResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesVzdumpExtractconfigWithHttpInfo(node: kotlin.String, volume: kotlin.String) : ApiResponse<NodesVzdumpExtractconfigResponse?> {
        val localVariableConfig = nodesVzdumpExtractconfigRequestConfig(node = node, volume = volume)

        return request<Unit, NodesVzdumpExtractconfigResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesVzdumpExtractconfig
     *
     * @param node The cluster node name.
     * @param volume Volume identifier
     * @return RequestConfig
     */
    fun nodesVzdumpExtractconfigRequestConfig(node: kotlin.String, volume: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("volume", listOf(volume.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/vzdump/extractconfig".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /nodes/{node}/vzdump
     * Create backup
     * Create backup.  Permissions: The user needs &#39;VM.Backup&#39; permissions on any VM, and &#39;Datastore.AllocateSpace&#39; on the backup storage (and fleecing storage when fleecing is used). The &#39;tmpdir&#39;, &#39;dumpdir&#39;, &#39;script&#39; and &#39;job-id&#39; parameters are restricted to the &#39;root@pam&#39; user. The &#39;prune-backups&#39; setting requires &#39;Datastore.Allocate&#39; on the backup storage. The &#39;bwlimit&#39;, &#39;performance&#39; and &#39;ionice&#39; parameters require &#39;Sys.Modify&#39; on &#39;/&#39;.
     * @param node Only run if executed on this node.
     * @param nodesVzdumpVzdumpRequest  (optional)
     * @return NodesVzdumpVzdumpResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesVzdumpVzdump(node: kotlin.String, nodesVzdumpVzdumpRequest: NodesVzdumpVzdumpRequest? = null) : NodesVzdumpVzdumpResponse {
        val localVarResponse = nodesVzdumpVzdumpWithHttpInfo(node = node, nodesVzdumpVzdumpRequest = nodesVzdumpVzdumpRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesVzdumpVzdumpResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /nodes/{node}/vzdump
     * Create backup
     * Create backup.  Permissions: The user needs &#39;VM.Backup&#39; permissions on any VM, and &#39;Datastore.AllocateSpace&#39; on the backup storage (and fleecing storage when fleecing is used). The &#39;tmpdir&#39;, &#39;dumpdir&#39;, &#39;script&#39; and &#39;job-id&#39; parameters are restricted to the &#39;root@pam&#39; user. The &#39;prune-backups&#39; setting requires &#39;Datastore.Allocate&#39; on the backup storage. The &#39;bwlimit&#39;, &#39;performance&#39; and &#39;ionice&#39; parameters require &#39;Sys.Modify&#39; on &#39;/&#39;.
     * @param node Only run if executed on this node.
     * @param nodesVzdumpVzdumpRequest  (optional)
     * @return ApiResponse<NodesVzdumpVzdumpResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesVzdumpVzdumpWithHttpInfo(node: kotlin.String, nodesVzdumpVzdumpRequest: NodesVzdumpVzdumpRequest?) : ApiResponse<NodesVzdumpVzdumpResponse?> {
        val localVariableConfig = nodesVzdumpVzdumpRequestConfig(node = node, nodesVzdumpVzdumpRequest = nodesVzdumpVzdumpRequest)

        return request<NodesVzdumpVzdumpRequest, NodesVzdumpVzdumpResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesVzdumpVzdump
     *
     * @param node Only run if executed on this node.
     * @param nodesVzdumpVzdumpRequest  (optional)
     * @return RequestConfig
     */
    fun nodesVzdumpVzdumpRequestConfig(node: kotlin.String, nodesVzdumpVzdumpRequest: NodesVzdumpVzdumpRequest?) : RequestConfig<NodesVzdumpVzdumpRequest> {
        val localVariableBody = nodesVzdumpVzdumpRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/nodes/{node}/vzdump".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
