/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.clientapi.pve.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import dev.clientapi.pve.models.NodesStatusNodeCmdRequest
import dev.clientapi.pve.models.NodesStatusNodeCmdResponse
import dev.clientapi.pve.models.NodesStatusStatusResponse
import dev.clientapi.pve.models.PveError

import com.squareup.moshi.Json

import dev.clientapi.pve.infrastructure.ApiClient
import dev.clientapi.pve.infrastructure.ApiResponse
import dev.clientapi.pve.infrastructure.ClientException
import dev.clientapi.pve.infrastructure.ClientError
import dev.clientapi.pve.infrastructure.ServerException
import dev.clientapi.pve.infrastructure.ServerError
import dev.clientapi.pve.infrastructure.MultiValueMap
import dev.clientapi.pve.infrastructure.PartConfig
import dev.clientapi.pve.infrastructure.RequestConfig
import dev.clientapi.pve.infrastructure.RequestMethod
import dev.clientapi.pve.infrastructure.ResponseType
import dev.clientapi.pve.infrastructure.Success
import dev.clientapi.pve.infrastructure.toMultiValue

open class NodesStatusApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8006/api2/json")
        }
    }

    /**
     * POST /nodes/{node}/status
     * Reboot or shutdown a node
     * Reboot or shutdown a node.
     * @param node The cluster node name.
     * @param nodesStatusNodeCmdRequest 
     * @return NodesStatusNodeCmdResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesStatusNodeCmd(node: kotlin.String, nodesStatusNodeCmdRequest: NodesStatusNodeCmdRequest) : NodesStatusNodeCmdResponse {
        val localVarResponse = nodesStatusNodeCmdWithHttpInfo(node = node, nodesStatusNodeCmdRequest = nodesStatusNodeCmdRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesStatusNodeCmdResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /nodes/{node}/status
     * Reboot or shutdown a node
     * Reboot or shutdown a node.
     * @param node The cluster node name.
     * @param nodesStatusNodeCmdRequest 
     * @return ApiResponse<NodesStatusNodeCmdResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesStatusNodeCmdWithHttpInfo(node: kotlin.String, nodesStatusNodeCmdRequest: NodesStatusNodeCmdRequest) : ApiResponse<NodesStatusNodeCmdResponse?> {
        val localVariableConfig = nodesStatusNodeCmdRequestConfig(node = node, nodesStatusNodeCmdRequest = nodesStatusNodeCmdRequest)

        return request<NodesStatusNodeCmdRequest, NodesStatusNodeCmdResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesStatusNodeCmd
     *
     * @param node The cluster node name.
     * @param nodesStatusNodeCmdRequest 
     * @return RequestConfig
     */
    fun nodesStatusNodeCmdRequestConfig(node: kotlin.String, nodesStatusNodeCmdRequest: NodesStatusNodeCmdRequest) : RequestConfig<NodesStatusNodeCmdRequest> {
        val localVariableBody = nodesStatusNodeCmdRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/nodes/{node}/status".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /nodes/{node}/status
     * Read node status
     * Read node status
     * @param node The cluster node name.
     * @return NodesStatusStatusResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesStatusStatus(node: kotlin.String) : NodesStatusStatusResponse {
        val localVarResponse = nodesStatusStatusWithHttpInfo(node = node)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesStatusStatusResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/status
     * Read node status
     * Read node status
     * @param node The cluster node name.
     * @return ApiResponse<NodesStatusStatusResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesStatusStatusWithHttpInfo(node: kotlin.String) : ApiResponse<NodesStatusStatusResponse?> {
        val localVariableConfig = nodesStatusStatusRequestConfig(node = node)

        return request<Unit, NodesStatusStatusResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesStatusStatus
     *
     * @param node The cluster node name.
     * @return RequestConfig
     */
    fun nodesStatusStatusRequestConfig(node: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/status".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
