// Auto-generated by scripts/sdk-facades.ts. Do not edit.

package dev.clientapi.pve

import okhttp3.Call
import dev.clientapi.pve.infrastructure.ApiClient

class Pve(
    basePath: String =
        System.getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8006/api2/json"),
    httpClient: Call.Factory = ApiClient.defaultClient,
) : Client(basePath, httpClient)
