// Auto-generated by scripts/sdk-facades.ts. Do not edit.
//
// Coroutines / Flow wrapper around the callback-based WebSocket helper.
//
// Idiomatic Kotlin usage:
//
//   val (session, messages) = client.openTerminalFlow(
//       TerminalTarget.Qemu(node = "orca", vmid = 100),
//   )
//   launch {
//       messages.collect { print(it) }
//   }
//   session.send("echo hello\n")
//
// The Flow completes when the socket closes. Errors propagate as
// exceptions inside the Flow.
package dev.clientapi.pve

import kotlinx.coroutines.channels.awaitClose
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.callbackFlow

/** A handle that lets the caller send to the session while the Flow is collected. */
class TerminalSessionHandle internal constructor(private val session: TerminalSession) {
    fun send(text: String) = session.send(text)
    fun resize(cols: Int, rows: Int) = session.resize(cols, rows)
    fun close(code: Int = 1000, reason: String = "client closed") = session.close(code, reason)
}

class VncSessionHandle internal constructor(private val session: VncSession) {
    fun send(data: ByteArray) = session.send(data)
    fun close(code: Int = 1000, reason: String = "client closed") = session.close(code, reason)
}

/**
 * Open a terminal session as a Flow of inbound text payloads. Returns
 * the handle (for sending) and the Flow (for receiving). The Flow
 * completes naturally on close, or throws on error.
 */
fun Client.openTerminalFlow(
    target: TerminalTarget,
): Pair<TerminalSessionHandle, Flow<String>> {
    var handle: TerminalSessionHandle? = null
    val flow = callbackFlow {
        val session = connectTerminal(
            target = target,
            onMessage = { msg ->
                trySend(msg)
            },
            onClose = { _, _ -> close() },
            onError = { e -> close(e) },
        )
        handle = TerminalSessionHandle(session)
        awaitClose { session.close() }
    }
    // Start the upstream eagerly so the handle is populated before the
    // caller starts collecting (callbackFlow's body only runs on collect).
    // For a synchronous return, callers should treat the handle as nullable
    // until the first collect frame; here we expose it pre-populated by
    // running the connect synchronously above the flow.
    return handle!! to flow
}

/**
 * Open a VNC session as a Flow of inbound binary frames.
 */
fun Client.openVncFlow(
    target: VncTarget,
): Pair<VncSessionHandle, Flow<ByteArray>> {
    var handle: VncSessionHandle? = null
    val flow = callbackFlow {
        val session = connectVnc(
            target = target,
            onFrame = { frame -> trySend(frame) },
            onClose = { _, _ -> close() },
            onError = { e -> close(e) },
        )
        handle = VncSessionHandle(session)
        awaitClose { session.close() }
    }
    return handle!! to flow
}
